// UI strings, keyed by screen. `en` is the source of truth; any key missing
// from `sv` falls back to English rather than breaking the screen.
//
// Interpolation uses {name} placeholders — see t() in lib/i18n.js.

export const STRINGS = {
  /* ================================================================ */
  en: {
    /* ---- common ---- */
    "common.appName": "StudyBuddy",
    "common.back": "Back",
    "common.backToMenu": "Back to menu",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.delete": "Delete",
    "common.loading": "Loading…",
    "common.progress": "Progress",
    "common.settings": "Settings",
    "common.newSet": "New set",
    "common.assignment": "Assignment",
    "common.test": "Test",
    "common.assignments": "Assignments",
    "common.tests": "Tests",
    "common.assignmentsLower": "assignments",
    "common.testsLower": "tests",
    "common.general": "General",
    "common.somethingWrong": "Something went wrong",
    "common.somethingWrongShort": "Something went wrong.",
    "common.questionOne": "{n} question",
    "common.questionMany": "{n} questions",
    "common.language": "Language",

    /* ---- dates ---- */
    "date.today": "Today",
    "date.tomorrow": "Tomorrow",
    "date.inDays": "in {n} days",
    "date.inWeekOne": "in 1 week",
    "date.inWeeks": "in {n} weeks",
    "date.inMonthOne": "in 1 month",
    "date.inMonths": "in {n} months",
    "date.overdueOne": "Overdue by 1 day",
    "date.overdueMany": "Overdue by {n} days",
    "date.dueNow": "due now",

    /* ---- menu ---- */
    "menu.title": "Menu",
    "menu.morning": "Good morning",
    "menu.afternoon": "Good afternoon",
    "menu.evening": "Good evening",
    "menu.subHasKey": "Pick something to study, or make a new set.",
    "menu.subNoKey": "Add a Claude key in Settings to generate sets from your own material.",
    "menu.searchPlaceholder": "Search sets…",
    "menu.searchAria": "Search your sets",
    "menu.sortAria": "Sort sets",
    "menu.sortRecent": "Recently added",
    "menu.sortName": "Name (A–Z)",
    "menu.sortWeakest": "Weakest first",
    "menu.chipAll": "All",
    "menu.newAssignment": "New assignment",
    "menu.newTest": "New test",
    "menu.inProgress": "In progress",
    "menu.answeredOf": "{n} of {total} answered",
    "menu.doneTimes": " · done {n}×",
    "menu.cardAria": "{title}, {subject}, {count} questions",
    "menu.cardAriaOpen": "{title}, {subject}, {count} questions, in progress",
    "menu.cardOptions": "Options for {title}",
    "menu.masteryTitle": "{pct}% mastery — how well you've been answering this set's topics",
    "menu.emptyFirstTitle": "Your library is empty",
    "menu.emptyFirstBody": "Make a set from your own notes, a PDF, a photo, or just a topic — or load the demo sets to see how it works.",
    "menu.emptyAssignTitle": "No assignments yet",
    "menu.emptyAssignBody": "Make one from your notes, a PDF, a photo, or just a topic.",
    "menu.emptyTestTitle": "No tests yet",
    "menu.emptyTestBody": "Create one the same way — just mark it as a test.",
    "menu.tryDemo": "Try a demo",
    "menu.demoAdded": "Demo sets added",
    "menu.demoFailed": "Couldn't load the demo sets",
    "menu.noMatch": "No {kind} match “{q}”. ",
    "menu.switchToTests": "{n} matching in Tests — switch",
    "menu.switchToAssignments": "{n} matching in Assignments — switch",
    "menu.itemRename": "Rename",
    "menu.itemEdit": "Edit questions",
    "menu.itemDuplicate": "Duplicate",
    "menu.itemDelete": "Delete",
    "menu.itemDue": "Due date",
    "menu.renamePrompt": "Rename this set:",
    "menu.renameEmpty": "A set needs a name",
    "menu.renamed": "Renamed",
    "menu.copiedAs": "Copied as “{title}”",
    "menu.deleteConfirm": "Delete “{title}”?\n\nThis can't be undone.",
    "menu.deleteConfirmAttempts": "Delete “{title}”?\n\nThis also removes {n} recorded attempt(s) from your history.\n\nThis can't be undone.",
    "menu.deleted": "Deleted",
    "menu.tileDue": "{n} due",
    "menu.tileDueSub": "Review across all sets",
    "menu.tileContinue": "Continue",
    "menu.tileContinueSub": "{title} · {n} of {total} answered",
    "menu.tileStreakOne": "{n}-day streak",
    "menu.tileStreak": "{n}-day streak",
    "menu.tileStreakSub": "See your progress",
    "menu.tileWeak": "Weak spots",
    "menu.tileWeakSub": "Practise what you keep missing",
    "menu.upcoming": "Upcoming",
    "menu.upcomingStudy": "Study",
    "menu.upcomingStudyAria": "Study {title} now",
    "menu.upcomingAll": "Show all ({n})",
    "menu.upcomingLess": "Show fewer",
    "menu.dueLabel": "Due {date}",

    /* ---- due date dialog ---- */
    "due.title": "Due date",
    "due.body": "When does “{title}” need to be done?",
    "due.field": "Date",
    "due.save": "Save date",
    "due.clear": "Clear date",
    "due.saved": "Due date set",
    "due.cleared": "Due date cleared",
    "due.invalid": "Pick a valid date",

    /* ---- session ---- */
    "session.questionOf": "Question {n} of {total} · {done} answered",
    "session.skippedSuffix": " · {n} skipped",
    "session.next": "Next",
    "session.finish": "Finish",
    "session.skip": "Skip for now",
    "session.exit": "Exit",
    "session.exitConfirm": "Leave this session?\n\nYour progress is saved — you can pick up where you left off.",
    "session.resumeTitle": "Pick up where you left off?",
    "session.resumeRemaining": "You answered {n} of {total} last time — {left} to go.",
    "session.resumeDone": "You answered {n} of {total} last time, so you're ready to finish.",
    "session.continue": "Continue",
    "session.startOver": "Start over",
    "session.testBanner": "Test mode: one attempt per question and no hints. The tutor will go through it with you afterwards.",
    "session.badgeReview": "Review",
    "session.badgePractice": "Practice",
    "session.badgeWeak": "Weak spots",
    "session.reviewTitle": "Review session",
    "session.practiceTitle": "Practice",
    "session.weakTitle": "Weak spots",
    "session.notFoundTitle": "Nothing to study here",
    "session.goneSet": "That set no longer exists.",
    "session.emptySet": "That set has no questions yet.",
    "session.goneQuestions": "These questions are no longer available.",
    "session.goneResult": "That result is no longer available.",
    "session.nothingDueTitle": "Nothing due right now",
    "session.nothingDueBody": "Spaced repetition brings questions back just before you'd forget them. Come back tomorrow, or study a set to add more.",
    "session.nothingPractiseTitle": "Nothing to practise",
    "session.nothingPractiseBody": "You got everything right in that session.",
    "session.noWeakTitle": "No weak spots yet",
    "session.noWeakBody": "Finish a few sessions first — then this practises whatever you keep getting wrong.",
    "session.annCorrect": "Correct.",
    "session.annWrong": "Not correct. The tutor can help.",
    "session.annRecorded": "Answer recorded.",
    "session.annSkipped": "Skipped. You'll see this one again at the end.",
    "session.annQuestion": "Question {n} of {total}.",
    "session.needHint": "Need a hint?",
    "session.hideTutor": "Hide tutor",
    "session.shortcutsBtn": "Keyboard shortcuts",
    "session.shortcutTip": "Tip: press ? for keyboard shortcuts",

    /* ---- shortcuts sheet ---- */
    "keys.title": "Keyboard shortcuts",
    "keys.pick": "Pick a multiple-choice answer",
    "keys.enter": "Check your answer, then move on",
    "keys.next": "Next question",
    "keys.skip": "Skip for now",
    "keys.space": "Flip a flashcard",
    "keys.show": "Show this list",
    "keys.close": "Close",

    /* ---- questions ---- */
    "q.check": "Check answer",
    "q.submit": "Submit answer",
    "q.checking": "Checking…",
    "q.submitting": "Submitting…",
    "q.recorded": "Answer recorded.",
    "q.leftBlank": "Left blank.",
    "q.correct": "Correct!",
    "q.notQuite": "Not quite — have another go.",
    "q.stillNotRight": "Still not right. Read the tutor's hint, then pick again — or reveal the answer below.",
    "q.reveal": "Reveal answer & continue",
    "q.answerIs": "The answer is {letter}.",
    "q.typeAnswer": "Type your answer…",
    "q.yourAnswer": "Your answer",
    "q.modelAnswer": "Model answer:",
    "q.fullSolution": "Full solution:",
    "q.disagree": "Disagree with the marking? ",
    "q.appeal": "I think my answer was right",
    "q.appealDone": "Marked as correct. Have a look at the model answer anyway — it's easy to miss a bit.",
    "q.heuristicOk": "That covers the key ideas — check the details below.",
    "q.heuristicMiss": "This looks like it's missing some of the key ideas. Compare it with the model answer below.",
    "q.flipAria": "Flip card",
    "q.tapFlip": "Tap the card to flip, or press Space.",
    "q.rateAgain": "Again",
    "q.rateHard": "Hard",
    "q.rateGood": "Good",
    "q.rateEasy": "Easy",
    "q.workedPlaceholder": "Work it out here — the tutor on the right will help.",
    "q.workedPlaceholderTest": "Work it out here.",
    "q.yourWorking": "Your working",
    "q.showStep": "Show a step",
    "q.doneShowAnswer": "I'm done — show the answer",
    "q.reasoningGetThere": "Did your reasoning get there?",
    "q.yesHadIt": "Yes, I had it",
    "q.notQuiteBtn": "Not quite",
    "q.tutorRight": "I picked the right one!",
    "q.tutorWrongMc": "I chose \"{choice}\" and it's wrong. Can you help me see why?",
    "q.tutorGotIt": "I think I got that one.",
    "q.tutorWhatMissing": "Here's what I wrote: \"{answer}\". What am I missing?",
    "q.tutorForgot": "I couldn't remember this one. Can you help it stick?",
    "q.tutorRemembered": "Remembered it!",
    "q.tutorRevealedStep": "I've revealed step {n}. Can you nudge me toward the next bit?",

    /* ---- tutor ---- */
    "tutor.name": "StudyBuddy",
    "tutor.subLive": "your tutor",
    "tutor.subDemo": "your tutor · demo mode",
    "tutor.subLocked": "locked during the test",
    "tutor.lockedTitle": "I'm sitting this one out.",
    "tutor.lockedBody": "It's a test, so no hints — answer as best you can. When you finish I'll go through everything you missed with you.",
    "tutor.ask": "Ask the tutor…",
    "tutor.askAria": "Message the tutor",
    "tutor.send": "Send",
    "tutor.convAria": "Tutor conversation",
    "tutor.voiceAria": "Voice mode — coming soon",
    "tutor.voiceSoon": "soon",
    "tutor.voiceToast": "Voice mode is coming — you'll be able to talk through problems out loud.",
    "tutor.prefix": "Tutor: {text}",
    "tutor.snag": "The tutor hit a snag. Try again in a moment.",
    "tutor.firstThought": "Let's tackle this one. What's your first thought?",
    "tutor.scriptedCorrect": "That's right — well done!",
    "tutor.scriptedEncourage": "Give it another try — you're close.",

    /* ---- results ---- */
    "results.title": "Results",
    "results.great": "Great work! 🎉",
    "results.nice": "Nice effort 💪",
    "results.none": "No results to show",
    "results.correctOf": "{c} / {n} correct",
    "results.testSuffix": " · test",
    "results.tookSec": "Took {n}s",
    "results.tookMin": "Took {n} min",
    "results.tookHour": "Took {h}h {m}m",
    "results.topicMastery": "Topic mastery",
    "results.worthLook": "Worth another look",
    "results.practiseTheseOne": "Practise this now",
    "results.practiseTheseMany": "Practise these {n} now",
    "results.tutorSatOut": "The tutor sat out the test — it'll work through these with you now.",
    "results.tryAgain": "Try again",
    "results.reviewAgain": "Review again",
    "results.seeProgress": "See progress",

    /* ---- progress ---- */
    "prog.title": "Your progress",
    "prog.streak": "Study streak",
    "prog.streakDaysOne": "{n} day",
    "prog.streakDaysMany": "{n} days",
    "prog.streakAria": "Studied on {n} of the last 14 days",
    "prog.summary": "{days} studied · {sessions} completed",
    "prog.daysOne": "1 day",
    "prog.daysMany": "{n} days",
    "prog.sessionsOne": "1 session",
    "prog.sessionsMany": "{n} sessions",
    "prog.mastery": "Mastery by subject",
    "prog.masteryEmpty": "Finish a session to start building mastery scores. Weakest topics show first.",
    "prog.masteryAria": "{subject}: {pct}% mastery",
    "prog.practiseWeak": "Practise weak spots",
    "prog.due": "Due for review",
    "prog.dueCount": "Due for review ({n})",
    "prog.reviewToday": "Review today",
    "prog.reviewExplain": "“Review today” practises just these questions, pulled from every set.",
    "prog.nothingDue": "Nothing due right now. Spaced repetition brings questions back just before you'd forget them.",
    "prog.moreDue": "+ {n} more",

    /* ---- create ---- */
    "create.title": "New study set",
    "create.stepSource": "Source",
    "create.stepMaterial": "Material",
    "create.stepReview": "Review",
    "create.whereFrom": "Where should the questions come from?",
    "create.optPaste": "Paste text",
    "create.optPasteSub": "Notes, an article, a chapter",
    "create.optPdf": "Upload PDF",
    "create.optPdfSub": "A worksheet or textbook page",
    "create.optPhoto": "Upload photo",
    "create.optPhotoSub": "A picture of a page or board",
    "create.optTopic": "Just a topic",
    "create.optTopicSub": "e.g. “Grade 5 fractions”",
    "create.needKey": "Generating needs a Claude API key. ",
    "create.needKeyLink": "Add one in Settings",
    "create.needKeyTail": " — or explore the demo sets on the menu for now.",
    "create.material": "Study material",
    "create.materialPlaceholder": "Paste your notes or reading here…",
    "create.topic": "Topic",
    "create.topicPlaceholder": "e.g. The water cycle, Grade 4",
    "create.grade": "Year / age level",
    "create.gradePlaceholder": "e.g. Year 8 / age 13 (optional)",
    "create.pdfFile": "PDF file",
    "create.photo": "Photo",
    "create.reading": "Reading…",
    "create.extracted": "Extracted {n} characters from “{name}”.",
    "create.loadedFile": "Loaded “{name}”.",
    "create.readFail": "Could not read that file.",
    "create.subject": "Subject",
    "create.type": "Type",
    "create.typeAssignment": "Assignment (practice)",
    "create.typeTest": "Test (quiz)",
    "create.howMany": "How many questions",
    "create.generate": "Generate questions",
    "create.generating": "Writing your questions…",
    "create.generatingSub": "This usually takes 10–30 seconds.",
    "create.needMaterial": "Add some material or a topic first.",
    "create.genFailed": "Generation failed. Try again or simplify the material.",
    "create.setTitle": "Title",
    "create.setTitleAria": "Set title",
    "create.countNote": "{n} · edit anything below, then save.",
    "create.addQuestion": "+ question",
    "create.saveSet": "Save set",
    "create.addAtLeastOne": "Add at least one question.",
    "create.giveName": "Give the set a name.",
    "create.saved": "Saved!",
    "create.dueDate": "Due date (optional)",

    /* ---- edit ---- */
    "edit.title": "Edit set",
    "edit.pageTitle": "Edit — {title}",
    "edit.gone": "That set no longer exists",
    "edit.saveChanges": "Save changes",
    "edit.saved": "Saved",
    "edit.giveName": "Give the set a name",
    "edit.needQuestion": "A set needs at least one question",
    "edit.dueDate": "Due date",

    /* ---- question editor ---- */
    "ed.none": "No questions yet — add one below.",
    "ed.qBadge": "Q{n}",
    "ed.qTextAria": "Question {n} text",
    "ed.question": "Question",
    "ed.type": "Question type",
    "ed.kindMc": "Multiple choice",
    "ed.kindText": "Short answer",
    "ed.kindFlash": "Flashcard",
    "ed.kindWorked": "Worked problem",
    "ed.topicPlaceholder": "topic",
    "ed.topicAria": "Topic tag",
    "ed.choiceCorrect": "Choice {letter} is correct",
    "ed.choiceAria": "Choice {letter}",
    "ed.removeChoice": "Remove choice {letter}",
    "ed.selectCorrect": "Select the radio button next to the correct choice.",
    "ed.addChoice": "+ choice",
    "ed.backOfCard": "Back of card",
    "ed.modelAnswer": "Model answer",
    "ed.answerAria": "Answer",
    "ed.deleteQuestion": "Delete question {n}",
    "ed.deleteQuestionTitle": "Delete question",

    /* ---- settings ---- */
    "set.title": "Settings",
    "set.lookFeel": "Look & feel",
    "set.aiTitle": "AI",
    "set.theme": "Theme",
    "set.themeSystem": "Match my device",
    "set.themeLight": "Light",
    "set.themeDark": "Dark",
    "set.themeUpdated": "Theme updated",
    "set.language": "Language",
    "set.languageNote": "Changes the interface, and asks the tutor to reply in that language. Sets you already made keep the language they were written in.",
    "set.langUpdated": "Language updated",
    "set.sound": "Sound effects",
    "set.soundNote": "A soft chime for right and wrong answers, and a little fanfare for a strong result.",
    "set.soundOn": "On",
    "set.soundOff": "Off",
    "set.soundUpdated": "Sound updated",
    "set.keyTitle": "Claude API key",
    "set.keyBody": "Needed to generate assignments from your material and for live tutoring. Without it, StudyBuddy runs in demo mode on the sample content.",
    "set.key": "Key",
    "set.show": "Show",
    "set.hide": "Hide",
    "set.save": "Save",
    "set.keySaved": "Key saved — live tutoring is on",
    "set.keyCleared": "Key cleared — demo mode",
    "set.keyWarning": " Your key is stored only in this browser (localStorage). That's fine for personal use. Don't put this app on a public website until a small backend holds the key instead — anyone visiting could otherwise use your key.",
    "set.getKeyAt": "Get a key at ",
    "set.billed": ". Usage is billed to your Anthropic account.",
    "set.modelTitle": "Model & tutor",
    "set.modelIntro": "StudyBuddy uses different Claude models for different jobs, so you're not paying top rates to mark a one-line answer.",
    "set.qualityCost": "Quality & cost",
    "set.presetUpdated": "Model preset updated",
    "preset.balanced": "Balanced — recommended",
    "preset.balancedHint": "Best model writes your questions; a lighter one marks answers. Good quality, much lower cost.",
    "preset.best": "Best quality",
    "preset.bestHint": "Claude Opus 5 for everything. The strongest tutoring, and the most expensive.",
    "preset.cheapest": "Lowest cost",
    "preset.cheapestHint": "Fast and cheap throughout. Fine for drilling facts; weaker at explaining hard ideas.",
    "set.jobWriting": "Writing a set",
    "set.jobTutoring": "Tutoring you",
    "set.jobMarking": "Marking answers",
    "set.whenPerSet": "once per set",
    "set.whenEveryMsg": "every message",
    "set.whenEveryAnswer": "every written answer",
    "set.replyLength": "Tutor reply length",
    "set.verbConcise": "Concise — short hints",
    "set.verbNormal": "Normal (default)",
    "set.verbDetailed": "Detailed — fuller explanations",
    "set.tutorStyleUpdated": "Tutor style updated",
    "set.demoTitle": "Demo content",
    "set.demoNone": "Two ready-made sets (Photosynthesis Basics, Ancient Rome Quiz) you can try without an API key — the tutor works in demo mode too.",
    "set.demoPartial": "{loaded} of {total} demo sets are in your library. You can add the missing one back, or clear them out.",
    "set.demoAll": "Both demo sets are in your library. They behave like any other set — study, edit, or delete them.",
    "set.demoLoad": "Load demo sets",
    "set.demoAddMissing": "Add the missing one",
    "set.demoRemove": "Remove demo sets",
    "set.demoRemoveConfirm": "Remove the demo sets from your library?\n\nAny attempts you made on them stay in your history.",
    "set.demoRemoved": "Demo sets removed",
    "set.demoAddedOne": "Added 1 demo set",
    "set.demoAddedMany": "Added {n} demo sets",
    "set.demoAlready": "Already in your library",
    "set.demoFailed": "Couldn't load the demo sets",
    "set.dataTitle": "Your data",
    "set.dataBody": "Everything (assignments, attempts, progress) lives in this browser.",
    "set.export": "Export JSON",
    "set.wipe": "Wipe all data",
    "set.wipeConfirm": "Delete all sets, attempts, and progress?\n\nThis can't be undone. Export a backup first if you want to keep it.",
    "set.wiped": "Data wiped",
    "set.backupDownloaded": "Backup downloaded",
    "set.roadmap": "Roadmap",
    "set.roadVoice": "Voice chat — talk through problems out loud",
    "set.roadAccounts": "Accounts & sync — use StudyBuddy on any device",
    "set.roadTeacher": "Parent / teacher view — assign work and track progress",
    "set.roadShare": "Share assignment sets with a friend",

    /* ---- errors ---- */
    "err.network": "Network error — check your connection.",
    "err.badKey": "That API key was rejected. Check it in Settings.",
    "err.rateLimited": "Rate limited by the API — wait a moment and try again.",
    "err.api": "API error {status}",
    "err.apiDetail": "API error {status}: {detail}",
    "err.tutorUnavailable": "Tutor unavailable (API {status}).",
    "err.pdfNoLib": "PDF reader failed to load. Refresh and try again.",
    "err.pdfNoText": "Couldn't find selectable text in that PDF. If it's a scan, upload it as a photo instead.",
    "err.imageType": "Please use a PNG, JPG, WEBP, or GIF image.",
    "err.imageSize": "That image is over 5 MB — try a smaller photo.",
    "err.readFile": "Could not read that file.",
  },

  /* ================================================================ */
  sv: {
    /* ---- common ---- */
    "common.appName": "StudyBuddy",
    "common.back": "Tillbaka",
    "common.backToMenu": "Tillbaka till menyn",
    "common.cancel": "Avbryt",
    "common.save": "Spara",
    "common.close": "Stäng",
    "common.delete": "Ta bort",
    "common.loading": "Laddar…",
    "common.progress": "Framsteg",
    "common.settings": "Inställningar",
    "common.newSet": "Nytt set",
    "common.assignment": "Uppgift",
    "common.test": "Prov",
    "common.assignments": "Uppgifter",
    "common.tests": "Prov",
    "common.assignmentsLower": "uppgifter",
    "common.testsLower": "prov",
    "common.general": "Allmänt",
    "common.somethingWrong": "Något gick fel",
    "common.somethingWrongShort": "Något gick fel.",
    "common.questionOne": "{n} fråga",
    "common.questionMany": "{n} frågor",
    "common.language": "Språk",

    /* ---- dates ---- */
    "date.today": "Idag",
    "date.tomorrow": "Imorgon",
    "date.inDays": "om {n} dagar",
    "date.inWeekOne": "om 1 vecka",
    "date.inWeeks": "om {n} veckor",
    "date.inMonthOne": "om 1 månad",
    "date.inMonths": "om {n} månader",
    "date.overdueOne": "1 dag försenad",
    "date.overdueMany": "{n} dagar försenad",
    "date.dueNow": "dags nu",

    /* ---- menu ---- */
    "menu.title": "Meny",
    "menu.morning": "God morgon",
    "menu.afternoon": "God eftermiddag",
    "menu.evening": "God kväll",
    "menu.subHasKey": "Välj något att plugga på, eller skapa ett nytt set.",
    "menu.subNoKey": "Lägg till en Claude-nyckel i Inställningar för att skapa set av ditt eget material.",
    "menu.searchPlaceholder": "Sök bland set…",
    "menu.searchAria": "Sök bland dina set",
    "menu.sortAria": "Sortera set",
    "menu.sortRecent": "Senast tillagda",
    "menu.sortName": "Namn (A–Ö)",
    "menu.sortWeakest": "Svagast först",
    "menu.chipAll": "Alla",
    "menu.newAssignment": "Ny uppgift",
    "menu.newTest": "Nytt prov",
    "menu.inProgress": "Påbörjad",
    "menu.answeredOf": "{n} av {total} besvarade",
    "menu.doneTimes": " · gjord {n} ggr",
    "menu.cardAria": "{title}, {subject}, {count} frågor",
    "menu.cardAriaOpen": "{title}, {subject}, {count} frågor, påbörjad",
    "menu.cardOptions": "Alternativ för {title}",
    "menu.masteryTitle": "{pct}% kunskapsnivå — hur bra det gått på det här settets områden",
    "menu.emptyFirstTitle": "Ditt bibliotek är tomt",
    "menu.emptyFirstBody": "Skapa ett set av dina egna anteckningar, en PDF, ett foto eller bara ett ämne — eller ladda demo-seten för att se hur det funkar.",
    "menu.emptyAssignTitle": "Inga uppgifter än",
    "menu.emptyAssignBody": "Skapa en av dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "menu.emptyTestTitle": "Inga prov än",
    "menu.emptyTestBody": "Skapa ett på samma sätt — markera det bara som prov.",
    "menu.tryDemo": "Testa en demo",
    "menu.demoAdded": "Demo-set tillagda",
    "menu.demoFailed": "Kunde inte ladda demo-seten",
    "menu.noMatch": "Inga {kind} matchar ”{q}”. ",
    "menu.switchToTests": "{n} träffar under Prov — byt dit",
    "menu.switchToAssignments": "{n} träffar under Uppgifter — byt dit",
    "menu.itemRename": "Byt namn",
    "menu.itemEdit": "Redigera frågor",
    "menu.itemDuplicate": "Duplicera",
    "menu.itemDelete": "Ta bort",
    "menu.itemDue": "Deadline",
    "menu.renamePrompt": "Byt namn på settet:",
    "menu.renameEmpty": "Settet behöver ett namn",
    "menu.renamed": "Namnet ändrat",
    "menu.copiedAs": "Kopierad som ”{title}”",
    "menu.deleteConfirm": "Ta bort ”{title}”?\n\nDet går inte att ångra.",
    "menu.deleteConfirmAttempts": "Ta bort ”{title}”?\n\nDet tar också bort {n} sparade försök ur din historik.\n\nDet går inte att ångra.",
    "menu.deleted": "Borttagen",
    "menu.tileDue": "{n} att repetera",
    "menu.tileDueSub": "Repetera från alla set",
    "menu.tileContinue": "Fortsätt",
    "menu.tileContinueSub": "{title} · {n} av {total} besvarade",
    "menu.tileStreakOne": "{n} dag i rad",
    "menu.tileStreak": "{n} dagar i rad",
    "menu.tileStreakSub": "Se dina framsteg",
    "menu.tileWeak": "Svaga punkter",
    "menu.tileWeakSub": "Öva på det du ofta missar",
    "menu.upcoming": "Kommande",
    "menu.upcomingStudy": "Plugga",
    "menu.upcomingStudyAria": "Plugga {title} nu",
    "menu.upcomingAll": "Visa alla ({n})",
    "menu.upcomingLess": "Visa färre",
    "menu.dueLabel": "Deadline {date}",

    /* ---- due date dialog ---- */
    "due.title": "Deadline",
    "due.body": "När ska ”{title}” vara klar?",
    "due.field": "Datum",
    "due.save": "Spara datum",
    "due.clear": "Ta bort datum",
    "due.saved": "Deadline satt",
    "due.cleared": "Deadline borttagen",
    "due.invalid": "Välj ett giltigt datum",

    /* ---- session ---- */
    "session.questionOf": "Fråga {n} av {total} · {done} besvarade",
    "session.skippedSuffix": " · {n} överhoppade",
    "session.next": "Nästa",
    "session.finish": "Slutför",
    "session.skip": "Hoppa över",
    "session.exit": "Lämna",
    "session.exitConfirm": "Lämna passet?\n\nDina framsteg sparas — du kan fortsätta där du slutade.",
    "session.resumeTitle": "Fortsätta där du slutade?",
    "session.resumeRemaining": "Du svarade på {n} av {total} förra gången — {left} kvar.",
    "session.resumeDone": "Du svarade på {n} av {total} förra gången, så du är redo att slutföra.",
    "session.continue": "Fortsätt",
    "session.startOver": "Börja om",
    "session.testBanner": "Provläge: ett försök per fråga och inga tips. Handledaren går igenom allt med dig efteråt.",
    "session.badgeReview": "Repetition",
    "session.badgePractice": "Övning",
    "session.badgeWeak": "Svaga punkter",
    "session.reviewTitle": "Repetitionspass",
    "session.practiceTitle": "Övning",
    "session.weakTitle": "Svaga punkter",
    "session.notFoundTitle": "Inget att plugga på här",
    "session.goneSet": "Det settet finns inte längre.",
    "session.emptySet": "Det settet har inga frågor än.",
    "session.goneQuestions": "De här frågorna finns inte längre.",
    "session.goneResult": "Det resultatet finns inte längre.",
    "session.nothingDueTitle": "Inget att repetera just nu",
    "session.nothingDueBody": "Repetition tar tillbaka frågor precis innan du hinner glömma dem. Kom tillbaka imorgon, eller plugga ett set för att lägga till fler.",
    "session.nothingPractiseTitle": "Inget att öva på",
    "session.nothingPractiseBody": "Du hade allt rätt i det passet.",
    "session.noWeakTitle": "Inga svaga punkter än",
    "session.noWeakBody": "Gör några pass först — sedan övar det här på det du ofta svarar fel på.",
    "session.annCorrect": "Rätt.",
    "session.annWrong": "Fel. Handledaren kan hjälpa.",
    "session.annRecorded": "Svaret sparat.",
    "session.annSkipped": "Överhoppad. Du får se den igen på slutet.",
    "session.annQuestion": "Fråga {n} av {total}.",
    "session.needHint": "Behöver du ett tips?",
    "session.hideTutor": "Dölj handledaren",
    "session.shortcutsBtn": "Kortkommandon",
    "session.shortcutTip": "Tips: tryck på ? för kortkommandon",

    /* ---- shortcuts sheet ---- */
    "keys.title": "Kortkommandon",
    "keys.pick": "Välj ett svarsalternativ",
    "keys.enter": "Rätta ditt svar, gå sedan vidare",
    "keys.next": "Nästa fråga",
    "keys.skip": "Hoppa över",
    "keys.space": "Vänd ett minneskort",
    "keys.show": "Visa den här listan",
    "keys.close": "Stäng",

    /* ---- questions ---- */
    "q.check": "Rätta svaret",
    "q.submit": "Skicka svar",
    "q.checking": "Rättar…",
    "q.submitting": "Skickar…",
    "q.recorded": "Svaret sparat.",
    "q.leftBlank": "Lämnat tomt.",
    "q.correct": "Rätt!",
    "q.notQuite": "Inte riktigt — försök igen.",
    "q.stillNotRight": "Fortfarande fel. Läs handledarens tips och välj igen — eller visa svaret nedan.",
    "q.reveal": "Visa svaret & fortsätt",
    "q.answerIs": "Rätt svar är {letter}.",
    "q.typeAnswer": "Skriv ditt svar…",
    "q.yourAnswer": "Ditt svar",
    "q.modelAnswer": "Exempelsvar:",
    "q.fullSolution": "Fullständig lösning:",
    "q.disagree": "Håller du inte med om rättningen? ",
    "q.appeal": "Jag tycker att mitt svar var rätt",
    "q.appealDone": "Markerat som rätt. Titta ändå på exempelsvaret — det är lätt att missa en bit.",
    "q.heuristicOk": "Det täcker huvudpoängerna — kolla detaljerna nedan.",
    "q.heuristicMiss": "Det här verkar sakna några av huvudpoängerna. Jämför med exempelsvaret nedan.",
    "q.flipAria": "Vänd kortet",
    "q.tapFlip": "Tryck på kortet för att vända, eller tryck på mellanslag.",
    "q.rateAgain": "Igen",
    "q.rateHard": "Svårt",
    "q.rateGood": "Bra",
    "q.rateEasy": "Lätt",
    "q.workedPlaceholder": "Räkna ut det här — handledaren till höger hjälper till.",
    "q.workedPlaceholderTest": "Räkna ut det här.",
    "q.yourWorking": "Dina uträkningar",
    "q.showStep": "Visa ett steg",
    "q.doneShowAnswer": "Jag är klar — visa svaret",
    "q.reasoningGetThere": "Kom ditt resonemang fram?",
    "q.yesHadIt": "Ja, jag hade rätt",
    "q.notQuiteBtn": "Inte riktigt",
    "q.tutorRight": "Jag valde rätt!",
    "q.tutorWrongMc": "Jag valde ”{choice}” och det var fel. Kan du hjälpa mig förstå varför?",
    "q.tutorGotIt": "Jag tror jag fick den rätt.",
    "q.tutorWhatMissing": "Så här skrev jag: ”{answer}”. Vad missar jag?",
    "q.tutorForgot": "Jag kom inte ihåg den här. Kan du hjälpa mig komma ihåg den?",
    "q.tutorRemembered": "Jag kom ihåg den!",
    "q.tutorRevealedStep": "Jag har visat steg {n}. Kan du knuffa mig mot nästa del?",

    /* ---- tutor ---- */
    "tutor.name": "StudyBuddy",
    "tutor.subLive": "din handledare",
    "tutor.subDemo": "din handledare · demoläge",
    "tutor.subLocked": "avstängd under provet",
    "tutor.lockedTitle": "Jag sitter över den här.",
    "tutor.lockedBody": "Det är ett prov, så inga tips — svara så gott du kan. När du är klar går jag igenom allt du missade med dig.",
    "tutor.ask": "Fråga handledaren…",
    "tutor.askAria": "Skriv till handledaren",
    "tutor.send": "Skicka",
    "tutor.convAria": "Samtal med handledaren",
    "tutor.voiceAria": "Röstläge — kommer snart",
    "tutor.voiceSoon": "snart",
    "tutor.voiceToast": "Röstläge är på väg — du kommer kunna prata igenom uppgifter högt.",
    "tutor.prefix": "Handledaren: {text}",
    "tutor.snag": "Handledaren fick problem. Försök igen om en stund.",
    "tutor.firstThought": "Nu tar vi den här. Vad är din första tanke?",
    "tutor.scriptedCorrect": "Precis rätt — snyggt!",
    "tutor.scriptedEncourage": "Testa en gång till — du är nära.",

    /* ---- results ---- */
    "results.title": "Resultat",
    "results.great": "Snyggt jobbat! 🎉",
    "results.nice": "Bra kämpat 💪",
    "results.none": "Inga resultat att visa",
    "results.correctOf": "{c} / {n} rätt",
    "results.testSuffix": " · prov",
    "results.tookSec": "Tog {n} s",
    "results.tookMin": "Tog {n} min",
    "results.tookHour": "Tog {h} h {m} min",
    "results.topicMastery": "Kunskapsnivå per område",
    "results.worthLook": "Värt att titta på igen",
    "results.practiseTheseOne": "Öva på den nu",
    "results.practiseTheseMany": "Öva på de {n} nu",
    "results.tutorSatOut": "Handledaren satt över provet — nu går den igenom de här med dig.",
    "results.tryAgain": "Försök igen",
    "results.reviewAgain": "Repetera igen",
    "results.seeProgress": "Se framsteg",

    /* ---- progress ---- */
    "prog.title": "Dina framsteg",
    "prog.streak": "Pluggstreak",
    "prog.streakDaysOne": "{n} dag",
    "prog.streakDaysMany": "{n} dagar",
    "prog.streakAria": "Pluggat {n} av de senaste 14 dagarna",
    "prog.summary": "{days} pluggade · {sessions} genomförda",
    "prog.daysOne": "1 dag",
    "prog.daysMany": "{n} dagar",
    "prog.sessionsOne": "1 pass",
    "prog.sessionsMany": "{n} pass",
    "prog.mastery": "Kunskapsnivå per ämne",
    "prog.masteryEmpty": "Gör klart ett pass för att börja bygga kunskapsnivåer. Svagaste området visas först.",
    "prog.masteryAria": "{subject}: {pct}% kunskapsnivå",
    "prog.practiseWeak": "Öva svaga punkter",
    "prog.due": "Att repetera",
    "prog.dueCount": "Att repetera ({n})",
    "prog.reviewToday": "Repetera idag",
    "prog.reviewExplain": "”Repetera idag” övar bara på de här frågorna, hämtade från alla dina set.",
    "prog.nothingDue": "Inget att repetera just nu. Repetition tar tillbaka frågor precis innan du hinner glömma dem.",
    "prog.moreDue": "+ {n} till",

    /* ---- create ---- */
    "create.title": "Nytt pluggset",
    "create.stepSource": "Källa",
    "create.stepMaterial": "Material",
    "create.stepReview": "Granska",
    "create.whereFrom": "Var ska frågorna komma ifrån?",
    "create.optPaste": "Klistra in text",
    "create.optPasteSub": "Anteckningar, en artikel, ett kapitel",
    "create.optPdf": "Ladda upp PDF",
    "create.optPdfSub": "Ett arbetsblad eller en boksida",
    "create.optPhoto": "Ladda upp foto",
    "create.optPhotoSub": "En bild på en sida eller tavla",
    "create.optTopic": "Bara ett ämne",
    "create.optTopicSub": "t.ex. ”Bråk, årskurs 5”",
    "create.needKey": "Att skapa frågor kräver en Claude API-nyckel. ",
    "create.needKeyLink": "Lägg till en i Inställningar",
    "create.needKeyTail": " — eller testa demo-seten på menyn så länge.",
    "create.material": "Studiematerial",
    "create.materialPlaceholder": "Klistra in dina anteckningar eller din text här…",
    "create.topic": "Ämne",
    "create.topicPlaceholder": "t.ex. Vattnets kretslopp, årskurs 4",
    "create.grade": "Årskurs / ålder",
    "create.gradePlaceholder": "t.ex. årskurs 8 / 13 år (valfritt)",
    "create.pdfFile": "PDF-fil",
    "create.photo": "Foto",
    "create.reading": "Läser…",
    "create.extracted": "Hämtade {n} tecken från ”{name}”.",
    "create.loadedFile": "Laddade ”{name}”.",
    "create.readFail": "Kunde inte läsa filen.",
    "create.subject": "Ämne",
    "create.type": "Typ",
    "create.typeAssignment": "Uppgift (övning)",
    "create.typeTest": "Prov (quiz)",
    "create.howMany": "Hur många frågor",
    "create.generate": "Skapa frågor",
    "create.generating": "Skriver dina frågor…",
    "create.generatingSub": "Det tar oftast 10–30 sekunder.",
    "create.needMaterial": "Lägg till lite material eller ett ämne först.",
    "create.genFailed": "Det gick inte att skapa frågorna. Försök igen eller förenkla materialet.",
    "create.setTitle": "Titel",
    "create.setTitleAria": "Settets titel",
    "create.countNote": "{n} · ändra vad du vill nedan och spara sedan.",
    "create.addQuestion": "+ fråga",
    "create.saveSet": "Spara set",
    "create.addAtLeastOne": "Lägg till minst en fråga.",
    "create.giveName": "Ge settet ett namn.",
    "create.saved": "Sparat!",
    "create.dueDate": "Deadline (valfritt)",

    /* ---- edit ---- */
    "edit.title": "Redigera set",
    "edit.pageTitle": "Redigera — {title}",
    "edit.gone": "Det settet finns inte längre",
    "edit.saveChanges": "Spara ändringar",
    "edit.saved": "Sparat",
    "edit.giveName": "Ge settet ett namn",
    "edit.needQuestion": "Settet behöver minst en fråga",
    "edit.dueDate": "Deadline",

    /* ---- question editor ---- */
    "ed.none": "Inga frågor än — lägg till en nedan.",
    "ed.qBadge": "F{n}",
    "ed.qTextAria": "Text för fråga {n}",
    "ed.question": "Fråga",
    "ed.type": "Frågetyp",
    "ed.kindMc": "Flervalsfråga",
    "ed.kindText": "Kort svar",
    "ed.kindFlash": "Minneskort",
    "ed.kindWorked": "Steg-för-steg-uppgift",
    "ed.topicPlaceholder": "område",
    "ed.topicAria": "Områdesetikett",
    "ed.choiceCorrect": "Alternativ {letter} är rätt",
    "ed.choiceAria": "Alternativ {letter}",
    "ed.removeChoice": "Ta bort alternativ {letter}",
    "ed.selectCorrect": "Markera radioknappen bredvid det rätta alternativet.",
    "ed.addChoice": "+ alternativ",
    "ed.backOfCard": "Kortets baksida",
    "ed.modelAnswer": "Exempelsvar",
    "ed.answerAria": "Svar",
    "ed.deleteQuestion": "Ta bort fråga {n}",
    "ed.deleteQuestionTitle": "Ta bort fråga",

    /* ---- settings ---- */
    "set.title": "Inställningar",
    "set.lookFeel": "Utseende & ljud",
    "set.aiTitle": "AI",
    "set.theme": "Tema",
    "set.themeSystem": "Följ min enhet",
    "set.themeLight": "Ljust",
    "set.themeDark": "Mörkt",
    "set.themeUpdated": "Tema uppdaterat",
    "set.language": "Språk",
    "set.languageNote": "Byter språk i gränssnittet och ber handledaren svara på det språket. Set du redan skapat behåller språket de skrevs på.",
    "set.langUpdated": "Språk uppdaterat",
    "set.sound": "Ljudeffekter",
    "set.soundNote": "En mjuk ton för rätt och fel svar, och en liten fanfar vid ett bra resultat.",
    "set.soundOn": "På",
    "set.soundOff": "Av",
    "set.soundUpdated": "Ljud uppdaterat",
    "set.keyTitle": "Claude API-nyckel",
    "set.keyBody": "Behövs för att skapa uppgifter av ditt material och för live-handledning. Utan den kör StudyBuddy i demoläge på exempelinnehållet.",
    "set.key": "Nyckel",
    "set.show": "Visa",
    "set.hide": "Dölj",
    "set.save": "Spara",
    "set.keySaved": "Nyckel sparad — live-handledning är på",
    "set.keyCleared": "Nyckel borttagen — demoläge",
    "set.keyWarning": " Din nyckel sparas bara i den här webbläsaren (localStorage). Det är okej för personligt bruk. Lägg inte appen på en offentlig webbplats förrän en liten server håller nyckeln i stället — annars kan vem som helst som besöker den använda din nyckel.",
    "set.getKeyAt": "Hämta en nyckel på ",
    "set.billed": ". Användningen faktureras ditt Anthropic-konto.",
    "set.modelTitle": "Modell & handledare",
    "set.modelIntro": "StudyBuddy använder olika Claude-modeller för olika jobb, så du inte betalar toppris för att rätta ett enradssvar.",
    "set.qualityCost": "Kvalitet & kostnad",
    "set.presetUpdated": "Modellval uppdaterat",
    "preset.balanced": "Balanserat — rekommenderas",
    "preset.balancedHint": "Bästa modellen skriver dina frågor; en lättare rättar svaren. Bra kvalitet, mycket lägre kostnad.",
    "preset.best": "Bästa kvalitet",
    "preset.bestHint": "Claude Opus 5 till allt. Bästa handledningen, och den dyraste.",
    "preset.cheapest": "Lägsta kostnad",
    "preset.cheapestHint": "Snabbt och billigt hela vägen. Bra för att nöta fakta; svagare på att förklara svåra idéer.",
    "set.jobWriting": "Skriva ett set",
    "set.jobTutoring": "Handleda dig",
    "set.jobMarking": "Rätta svar",
    "set.whenPerSet": "en gång per set",
    "set.whenEveryMsg": "varje meddelande",
    "set.whenEveryAnswer": "varje skrivet svar",
    "set.replyLength": "Handledarens svarslängd",
    "set.verbConcise": "Kortfattat — korta tips",
    "set.verbNormal": "Normal (standard)",
    "set.verbDetailed": "Utförligt — fylligare förklaringar",
    "set.tutorStyleUpdated": "Handledarstil uppdaterad",
    "set.demoTitle": "Demoinnehåll",
    "set.demoNone": "Två färdiga set (Fotosyntes – grunderna, Antikens Rom) som du kan testa utan API-nyckel — handledaren funkar i demoläge också.",
    "set.demoPartial": "{loaded} av {total} demo-set finns i ditt bibliotek. Du kan lägga tillbaka det som saknas, eller rensa bort dem.",
    "set.demoAll": "Båda demo-seten finns i ditt bibliotek. De fungerar som vilket set som helst — plugga, redigera eller ta bort dem.",
    "set.demoLoad": "Ladda demo-set",
    "set.demoAddMissing": "Lägg tillbaka det som saknas",
    "set.demoRemove": "Ta bort demo-set",
    "set.demoRemoveConfirm": "Ta bort demo-seten ur ditt bibliotek?\n\nFörsök du gjort på dem finns kvar i historiken.",
    "set.demoRemoved": "Demo-set borttagna",
    "set.demoAddedOne": "1 demo-set tillagt",
    "set.demoAddedMany": "{n} demo-set tillagda",
    "set.demoAlready": "Finns redan i ditt bibliotek",
    "set.demoFailed": "Kunde inte ladda demo-seten",
    "set.dataTitle": "Dina data",
    "set.dataBody": "Allt (uppgifter, försök, framsteg) ligger i den här webbläsaren.",
    "set.export": "Exportera JSON",
    "set.wipe": "Radera all data",
    "set.wipeConfirm": "Radera alla set, försök och framsteg?\n\nDet går inte att ångra. Exportera en säkerhetskopia först om du vill behålla dem.",
    "set.wiped": "Data raderad",
    "set.backupDownloaded": "Säkerhetskopia nedladdad",
    "set.roadmap": "Kommande",
    "set.roadVoice": "Röstchatt — prata igenom uppgifter högt",
    "set.roadAccounts": "Konton & synk — använd StudyBuddy på alla enheter",
    "set.roadTeacher": "Förälder-/lärarvy — dela ut uppgifter och följ framsteg",
    "set.roadShare": "Dela set med en kompis",

    /* ---- errors ---- */
    "err.network": "Nätverksfel — kolla din uppkoppling.",
    "err.badKey": "API-nyckeln godtogs inte. Kontrollera den i Inställningar.",
    "err.rateLimited": "API:et begränsade anropen — vänta en stund och försök igen.",
    "err.api": "API-fel {status}",
    "err.apiDetail": "API-fel {status}: {detail}",
    "err.tutorUnavailable": "Handledaren är otillgänglig (API {status}).",
    "err.pdfNoLib": "PDF-läsaren kunde inte laddas. Ladda om sidan och försök igen.",
    "err.pdfNoText": "Hittade ingen markerbar text i den PDF:en. Om det är en inskanning, ladda upp den som foto i stället.",
    "err.imageType": "Använd en PNG-, JPG-, WEBP- eller GIF-bild.",
    "err.imageSize": "Bilden är över 5 MB — testa ett mindre foto.",
    "err.readFile": "Kunde inte läsa filen.",
  },
};
