// UI strings, keyed by screen. `en` is the source of truth; any key missing
// from `sv` falls back to English rather than breaking the screen.
//
// Interpolation uses {name} placeholders — see t() in lib/i18n.js.

export const STRINGS = {
  /* ================================================================ */
  en: {
    /* ---- common ---- */
    "common.appName": "StudyBuddy",
    "common.back": "Back",
    "common.backToMenu": "Back to menu",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.close": "Close",
    "common.delete": "Delete",
    "common.loading": "Loading…",
    "common.progress": "Progress",
    "common.settings": "Settings",
    "common.newSet": "New set",
    "common.assignment": "Assignment",
    "common.test": "Test",
    "common.assignments": "Assignments",
    "common.tests": "Tests",
    "common.assignmentsLower": "assignments",
    "common.testsLower": "tests",
    "common.general": "General",
    "common.somethingWrong": "Something went wrong",
    "common.somethingWrongShort": "Something went wrong.",
    "common.questionOne": "{n} question",
    "common.questionMany": "{n} questions",
    "common.language": "Language",

    /* ---- dates ---- */
    "date.today": "Today",
    "date.tomorrow": "Tomorrow",
    "date.inDays": "in {n} days",
    "date.inWeekOne": "in 1 week",
    "date.inWeeks": "in {n} weeks",
    "date.inMonthOne": "in 1 month",
    "date.inMonths": "in {n} months",
    "date.overdueOne": "Overdue by 1 day",
    "date.overdueMany": "Overdue by {n} days",
    "date.dueNow": "due now",

    /* ---- menu ---- */
    "menu.title": "Menu",
    "menu.morning": "Good morning",
    "menu.afternoon": "Good afternoon",
    "menu.evening": "Good evening",
    "menu.subHasKey": "Pick something to study, or make a new set.",
    "menu.subNoKey": "Running in demo mode — connect the tutor server for live generation and tutoring.",
    "menu.searchPlaceholder": "Search sets…",
    "menu.searchAria": "Search your sets",
    "menu.sortAria": "Sort sets",
    "menu.sortRecent": "Recently added",
    "menu.sortName": "Name (A–Z)",
    "menu.sortWeakest": "Weakest first",
    "menu.chipAll": "All",
    "menu.addSubject": "Add subject",
    "menu.addSubjectPh": "Subject name",
    "menu.subjectAdded": "Added “{name}” — pick it when you make a set",
    "menu.newAssignment": "New assignment",
    "menu.newTest": "New test",
    "menu.inProgress": "In progress",
    "menu.answeredOf": "{n} of {total} answered",
    "menu.doneTimes": " · done {n}×",
    "menu.cardAria": "{title}, {subject}, {count} questions",
    "menu.cardAriaOpen": "{title}, {subject}, {count} questions, in progress",
    "menu.cardOptions": "Options for {title}",
    "menu.masteryTitle": "{pct}% mastery — how well you've been answering this set's topics",
    "menu.emptyFirstTitle": "Your library is empty",
    "menu.emptyFirstBody": "Make a set from your own notes, a PDF, a photo, or just a topic — or load the demo sets to see how it works.",
    "menu.emptyAssignTitle": "No assignments yet",
    "menu.emptyAssignBody": "Make one from your notes, a PDF, a photo, or just a topic.",
    "menu.emptyTestTitle": "No tests yet",
    "menu.emptyTestBody": "Create one the same way — just mark it as a test.",
    "menu.tryDemo": "Try a demo",
    "menu.demoAdded": "Demo sets added",
    "menu.demoFailed": "Couldn't load the demo sets",
    "menu.noMatch": "No {kind} match “{q}”. ",
    "menu.switchToTests": "{n} matching in Tests — switch",
    "menu.switchToAssignments": "{n} matching in Assignments — switch",
    "menu.itemRename": "Rename",
    "menu.itemEdit": "Edit questions",
    "menu.itemDuplicate": "Duplicate",
    "menu.itemDelete": "Delete",
    "menu.itemDue": "Due date",
    "menu.renamePrompt": "Rename this set:",
    "menu.renameEmpty": "A set needs a name",
    "menu.renamed": "Renamed",
    "menu.copiedAs": "Copied as “{title}”",
    "menu.deleteConfirm": "Delete “{title}”?\n\nThis can't be undone.",
    "menu.deleteConfirmAttempts": "Delete “{title}”?\n\nThis also removes {n} recorded attempt(s) from your history.\n\nThis can't be undone.",
    "menu.deleted": "Deleted",
    "menu.tileDue": "{n} due",
    "menu.tileDueSub": "Review across all sets",
    "menu.tileContinue": "Continue",
    "menu.tileContinueSub": "{title} · {n} of {total} answered",
    "menu.tileStreakOne": "{n}-day streak",
    "menu.tileStreak": "{n}-day streak",
    "menu.tileStreakSub": "See your progress",
    "menu.tileWeak": "Weak spots",
    "menu.tileWeakSub": "Practise what you keep missing",
    "menu.upcoming": "Upcoming",
    "menu.upcomingStudy": "Study",
    "menu.upcomingStudyAria": "Study {title} now",
    "menu.upcomingAll": "Show all ({n})",
    "menu.upcomingLess": "Show fewer",
    "menu.calendarShowMonth": "Full month",
    "menu.calendarShowWeek": "This week",
    "menu.calendarEmptyWeek": "Nothing due this week.",
    "menu.nextTestToday": "Next test is today",
    "menu.nextTestTomorrow": "Next test is tomorrow",
    "menu.nextTestIn": "Next test in {n} days",
    "menu.nextTestOverdue": "Next test is overdue",
    "menu.upcomingCount": "Upcoming ({n})",
    "menu.dueLabel": "Due {date}",
    "menu.panelToday": "Today",
    "menu.panelSets": "Your sets",
    "menu.filter": "Filter",
    "menu.resumeGo": "Continue",
    "menu.achAllDone": "Every achievement unlocked — nicely done. 🎉",

    /* ---- due date dialog ---- */
    "due.title": "Due date",
    "due.body": "When does “{title}” need to be done?",
    "due.field": "Date",
    "due.save": "Save date",
    "due.clear": "Clear date",
    "due.saved": "Due date set",
    "due.cleared": "Due date cleared",
    "due.invalid": "Pick a valid date",

    /* ---- session ---- */
    "session.questionOf": "Question {n} of {total} · {done} answered",
    "session.skippedSuffix": " · {n} skipped",
    "session.next": "Next",
    "session.finish": "Finish",
    "session.skip": "Skip for now",
    "session.exit": "Exit",
    "session.exitConfirm": "Leave this session?\n\nYour progress is saved — you can pick up where you left off.",
    "session.resumeTitle": "Pick up where you left off?",
    "session.resumeRemaining": "You answered {n} of {total} last time — {left} to go.",
    "session.resumeDone": "You answered {n} of {total} last time, so you're ready to finish.",
    "session.continue": "Continue",
    "session.startOver": "Start over",
    "session.testBanner": "Test mode: one attempt per question and no hints. The tutor will go through it with you afterwards.",
    "session.badgeReview": "Review",
    "session.badgePractice": "Practice",
    "session.badgeWeak": "Weak spots",
    "session.reviewTitle": "Review session",
    "session.reviewMore": "{n} more due — come back after this batch.",
    "session.practiceTitle": "Practice",
    "session.weakTitle": "Weak spots",
    "session.notFoundTitle": "Nothing to study here",
    "session.goneSet": "That set no longer exists.",
    "session.emptySet": "That set has no questions yet.",
    "session.goneQuestions": "These questions are no longer available.",
    "session.goneResult": "That result is no longer available.",
    "session.nothingDueTitle": "Nothing due right now",
    "session.nothingDueBody": "Spaced repetition brings questions back just before you'd forget them. Come back tomorrow, or study a set to add more.",
    "session.nothingPractiseTitle": "Nothing to practise",
    "session.nothingPractiseBody": "You got everything right in that session.",
    "session.noWeakTitle": "No weak spots yet",
    "session.noWeakBody": "Finish a few sessions first — then this practises whatever you keep getting wrong.",
    "session.annCorrect": "Correct.",
    "session.annWrong": "Not correct. The tutor can help.",
    "session.annRecorded": "Answer recorded.",
    "session.annSkipped": "Skipped. You'll see this one again at the end.",
    "session.annQuestion": "Question {n} of {total}.",
    "session.needHint": "Need a hint?",
    "session.hideTutor": "Hide tutor",
    "session.shortcutsBtn": "Keyboard shortcuts",
    "session.shortcutTip": "Tip: press ? for keyboard shortcuts",

    /* ---- shortcuts sheet ---- */
    "keys.title": "Keyboard shortcuts",
    "keys.pick": "Pick a multiple-choice answer",
    "keys.enter": "Check your answer, then move on",
    "keys.next": "Next question",
    "keys.skip": "Skip for now",
    "keys.space": "Flip a flashcard",
    "keys.show": "Show this list",
    "keys.close": "Close",

    /* ---- questions ---- */
    "q.check": "Check answer",
    "q.submit": "Submit answer",
    "q.checking": "Checking…",
    "q.submitting": "Submitting…",
    "q.recorded": "Answer recorded.",
    "q.leftBlank": "Left blank.",
    "q.correct": "Correct!",
    "q.notQuite": "Not quite — have another go.",
    "q.stillNotRight": "Still not right. Read the tutor's hint, then pick again — or reveal the answer below.",
    "q.reveal": "Reveal answer & continue",
    "q.answerIs": "The answer is {letter}.",
    "q.typeAnswer": "Type your answer…",
    "q.yourAnswer": "Your answer",
    "q.modelAnswer": "Model answer:",
    "q.fullSolution": "Full solution:",
    "q.disagree": "Disagree with the marking? ",
    "q.appeal": "I think my answer was right",
    "q.appealDone": "Marked as correct. Have a look at the model answer anyway — it's easy to miss a bit.",
    "q.heuristicOk": "That covers the key ideas — check the details below.",
    "q.heuristicMiss": "This looks like it's missing some of the key ideas. Compare it with the model answer below.",
    "q.flipAria": "Flip card",
    "q.tapFlip": "Tap the card to flip, or press Space.",
    "q.flashcardRecallPlaceholder": "Type what you remember from the back of this card…",
    "q.gradingFailed": "Couldn't grade this automatically — here's the model answer to compare against.",
    "q.rateAgain": "Again",
    "q.rateHard": "Hard",
    "q.rateGood": "Good",
    "q.rateEasy": "Easy",
    "q.workedPlaceholder": "Work it out here — the tutor on the right will help.",
    "q.workedPlaceholderTest": "Work it out here.",
    "q.yourWorking": "Your working",
    "q.showStep": "Show a step",
    "q.doneShowAnswer": "I'm done — show the answer",
    "q.reasoningGetThere": "Did your reasoning get there?",
    "q.yesHadIt": "Yes, I had it",
    "q.notQuiteBtn": "Not quite",
    "q.tutorRight": "I picked the right one!",
    "q.tutorWrongMc": "I chose \"{choice}\" and it's wrong. Can you help me see why?",
    "q.tutorGotIt": "I think I got that one.",
    "q.tutorWhatMissing": "Here's what I wrote: \"{answer}\". What am I missing?",
    "q.tutorForgot": "I couldn't remember this one. Can you help it stick?",
    "q.tutorRemembered": "Remembered it!",
    "q.tutorRevealedStep": "I've revealed step {n}. Can you nudge me toward the next bit?",

    /* ---- tutor ---- */
    "tutor.name": "StudyBuddy",
    "tutor.subLive": "your tutor",
    "tutor.subDemo": "your tutor · demo mode",
    "tutor.subLocked": "locked during the test",
    "tutor.lockedTitle": "I'm sitting this one out.",
    "tutor.lockedBody": "It's a test, so no hints — answer as best you can. When you finish I'll go through everything you missed with you.",
    "tutor.ask": "Ask the tutor…",
    "tutor.askAria": "Message the tutor",
    "tutor.send": "Send",
    "tutor.convAria": "Tutor conversation",
    "tutor.voiceAria": "Voice mode — coming soon",
    "tutor.voiceSoon": "soon",
    "tutor.voiceToast": "Voice mode is coming — you'll be able to talk through problems out loud.",
    "tutor.prefix": "Tutor: {text}",
    "tutor.snag": "The tutor hit a snag. Try again in a moment.",
    "tutor.firstThought": "Let's tackle this one. What's your first thought?",
    "tutor.scriptedCorrect": "That's right — well done!",
    "tutor.scriptedEncourage": "Give it another try — you're close.",

    /* ---- results ---- */
    "results.title": "Results",
    "results.great": "Great work! 🎉",
    "results.nice": "Nice effort 💪",
    "results.none": "No results to show",
    "results.correctOf": "{c} / {n} correct",
    "results.testSuffix": " · test",
    "results.tookSec": "Took {n}s",
    "results.tookMin": "Took {n} min",
    "results.tookHour": "Took {h}h {m}m",
    "results.topicMastery": "Topic mastery",
    "results.worthLook": "Worth another look",
    "results.correctAnswerLabel": "Correct answer:",
    "results.practiseTheseOne": "Practise this now",
    "results.practiseTheseMany": "Practise these {n} now",
    "results.tutorSatOut": "The tutor sat out the test — it'll work through these with you now.",
    "results.tryAgain": "Try again",
    "results.reviewAgain": "Review again",
    "results.seeProgress": "See progress",

    /* ---- progress ---- */
    "prog.title": "Your progress",
    "prog.streak": "Study streak",
    "prog.streakDaysOne": "{n} day",
    "prog.streakDaysMany": "{n} days",
    "prog.streakAria": "Studied on {n} of the last 14 days",
    "prog.summary": "{days} studied · {sessions} completed",
    "prog.daysOne": "1 day",
    "prog.daysMany": "{n} days",
    "prog.sessionsOne": "1 session",
    "prog.sessionsMany": "{n} sessions",
    "prog.mastery": "Mastery by subject",
    "prog.masteryEmpty": "Finish a session to start building mastery scores. Weakest topics show first.",
    "prog.masteryAria": "{subject}: {pct}% mastery",
    "prog.practiseWeak": "Practise weak spots",
    "prog.due": "Due for review",
    "prog.dueCount": "Due for review ({n})",
    "prog.reviewToday": "Review today",
    "prog.reviewExplain": "“Review today” practises just these questions, pulled from every set.",
    "prog.nothingDue": "Nothing due right now. Spaced repetition brings questions back just before you'd forget them.",
    "prog.moreDue": "+ {n} more",

    /* ---- create ---- */
    "create.title": "New study set",
    "create.stepSource": "Source",
    "create.stepMaterial": "Material",
    "create.stepReview": "Review",
    "create.whereFrom": "Where should the questions come from?",
    "create.optPaste": "Paste text",
    "create.optPasteSub": "Notes, an article, a chapter",
    "create.optPdf": "Upload PDF",
    "create.optPdfSub": "A worksheet or textbook page",
    "create.optPhoto": "Upload photo",
    "create.optPhotoSub": "A picture of a page or board",
    "create.needKey": "Generating needs the tutor server. ",
    "create.needKeyLink": "Check its status in Settings",
    "create.needKeyTail": " — or explore the demo sets on the menu for now.",
    "create.material": "Study material",
    "create.materialPlaceholder": "Paste your notes or reading here…",
    "create.pdfFile": "PDF file",
    "create.photo": "Photo",
    "create.reading": "Reading…",
    "create.extracted": "Extracted {n} characters from “{name}”.",
    "create.loadedFile": "Loaded “{name}”.",
    "create.readFail": "Could not read that file.",
    "create.subject": "Subject",
    "create.type": "Type",
    "create.typeAssignment": "Assignment (practice)",
    "create.typeTest": "Test (quiz)",
    "create.howMany": "How many questions",
    "create.generate": "Generate questions",
    "create.generating": "Writing your questions…",
    "create.generatingSub": "This usually takes 10–30 seconds.",
    "create.needMaterial": "Add some material or a topic first.",
    "create.genFailed": "Generation failed. Try again or simplify the material.",
    "create.setTitle": "Title",
    "create.setTitleAria": "Set title",
    "create.countNote": "{n} · edit anything below, then save.",
    "create.addQuestion": "+ question",
    "create.saveSet": "Save set",
    "create.addAtLeastOne": "Add at least one question.",
    "create.giveName": "Give the set a name.",
    "create.saved": "Saved!",
    "create.dueDate": "Due date (optional)",

    /* ---- edit ---- */
    "edit.title": "Edit set",
    "edit.pageTitle": "Edit — {title}",
    "edit.gone": "That set no longer exists",
    "edit.saveChanges": "Save changes",
    "edit.saved": "Saved",
    "edit.giveName": "Give the set a name",
    "edit.needQuestion": "A set needs at least one question",
    "edit.dueDate": "Due date",

    /* ---- question editor ---- */
    "ed.none": "No questions yet — add one below.",
    "ed.qBadge": "Q{n}",
    "ed.qTextAria": "Question {n} text",
    "ed.question": "Question",
    "ed.type": "Question type",
    "ed.kindMc": "Multiple choice",
    "ed.kindText": "Short answer",
    "ed.kindFlash": "Flashcard",
    "ed.kindWorked": "Worked problem",
    "ed.topicPlaceholder": "topic",
    "ed.topicAria": "Topic tag",
    "ed.choiceCorrect": "Choice {letter} is correct",
    "ed.choiceAria": "Choice {letter}",
    "ed.removeChoice": "Remove choice {letter}",
    "ed.selectCorrect": "Select the radio button next to the correct choice.",
    "ed.addChoice": "+ choice",
    "ed.backOfCard": "Back of card",
    "ed.modelAnswer": "Model answer",
    "ed.answerAria": "Answer",
    "ed.deleteQuestion": "Delete question {n}",
    "ed.deleteQuestionTitle": "Delete question",

    /* ---- settings ---- */
    "set.title": "Settings",
    "set.lookFeel": "Look & feel",
    "set.aiTitle": "AI",
    "set.theme": "Theme",
    "set.themeSystem": "Match my device",
    "set.themeLight": "Light",
    "set.themeDark": "Dark",
    "set.themeUpdated": "Theme updated",
    "set.language": "Language",
    "set.languageNote": "Changes the interface, and asks the tutor to reply in that language. The demo sets follow it; your own sets keep the language they were created in.",
    "set.langUpdated": "Language updated",
    "set.sound": "Sound effects",
    "set.soundNote": "A soft chime for right and wrong answers, and a little fanfare for a strong result.",
    "set.soundOn": "On",
    "set.soundOff": "Off",
    "set.soundUpdated": "Sound updated",
    "set.keyTitle": "Claude API key",
    "set.keyBody": "Needed to generate assignments from your material and for live tutoring. Without it, StudyBuddy runs in demo mode on the sample content.",
    "set.key": "Key",
    "set.show": "Show",
    "set.hide": "Hide",
    "set.save": "Save",
    "set.keySaved": "Key saved — live tutoring is on",
    "set.keyCleared": "Key cleared — demo mode",
    "set.keyWarning": " Your key is stored only in this browser (localStorage). That's fine for personal use. Don't put this app on a public website until a small backend holds the key instead — anyone visiting could otherwise use your key.",
    "set.getKeyAt": "Get a key at ",
    "set.billed": ". Usage is billed to your Anthropic account.",
    "set.modelTitle": "Model & tutor",
    "set.modelIntro": "StudyBuddy uses different Claude models for different jobs, so you're not paying top rates to mark a one-line answer.",
    "set.qualityCost": "Quality & cost",
    "set.presetUpdated": "Model preset updated",
    "preset.balanced": "Balanced — recommended",
    "preset.balancedHint": "Best model writes your questions; a lighter one marks answers. Good quality, much lower cost.",
    "preset.best": "Best quality",
    "preset.bestHint": "Claude Opus 5 for everything. The strongest tutoring, and the most expensive.",
    "preset.cheapest": "Lowest cost",
    "preset.cheapestHint": "Fast and cheap throughout. Fine for drilling facts; weaker at explaining hard ideas.",
    "set.jobWriting": "Writing a set",
    "set.jobTutoring": "Tutoring you",
    "set.jobMarking": "Marking answers",
    "set.whenPerSet": "once per set",
    "set.whenEveryMsg": "every message",
    "set.whenEveryAnswer": "every written answer",
    "set.replyLength": "Tutor reply length",
    "set.verbConcise": "Concise — short hints",
    "set.verbNormal": "Normal (default)",
    "set.verbDetailed": "Detailed — fuller explanations",
    "set.tutorStyleUpdated": "Tutor style updated",
    "set.demoTitle": "Demo content",
    "set.demoNone": "Two ready-made sets (Photosynthesis Basics, Ancient Rome Quiz) you can try without an API key — the tutor works in demo mode too.",
    "set.demoPartial": "{loaded} of {total} demo sets are in your library. You can add the missing one back, or clear them out.",
    "set.demoAll": "Both demo sets are in your library. They behave like any other set — study, edit, or delete them.",
    "set.demoLoad": "Load demo sets",
    "set.demoAddMissing": "Add the missing one",
    "set.demoRemove": "Remove demo sets",
    "set.demoRemoveConfirm": "Remove the demo sets from your library?\n\nAny attempts you made on them stay in your history.",
    "set.demoRemoved": "Demo sets removed",
    "set.demoAddedOne": "Added 1 demo set",
    "set.demoAddedMany": "Added {n} demo sets",
    "set.demoAlready": "Already in your library",
    "set.demoFailed": "Couldn't load the demo sets",
    "set.dataTitle": "Your data",
    "set.dataBody": "Everything (assignments, attempts, progress) lives in this browser.",
    "set.export": "Export JSON",
    "set.wipe": "Wipe all data",
    "set.wipeConfirm": "Delete all sets, attempts, and progress?\n\nThis can't be undone. Export a backup first if you want to keep it.",
    "set.wiped": "Data wiped",
    "set.backupDownloaded": "Backup downloaded",
    "set.import": "Import",
    "set.importConfirm": "This replaces everything currently in the app with the file you picked.\n\nExport a backup first if you want to keep what's here now.",
    "set.imported": "Data imported.",
    "set.importBadFile": "That file couldn't be read as a StudyBuddy backup.",
    "set.importReadFail": "Couldn't read that file.",
    "set.recoveryFound": "We found data from last time that couldn't be loaded.",
    "set.recoveryDownload": "Download it",
    "set.recoveryDismiss": "Dismiss",
    "save.failedBanner": "Couldn't save — your browser's storage may be full.",
    "save.emergencyExport": "Download a backup now",
    "boot.failedTitle": "StudyBuddy couldn't start",
    "boot.failedBody": "Something went wrong loading your saved data. Your data is probably still on this device.",
    "boot.reload": "Try reloading",
    "boot.downloadData": "Download your saved data",
    "set.roadmap": "Roadmap",
    "set.roadVoice": "Voice chat — talk through problems out loud",
    "set.roadAccounts": "Accounts & sync — use StudyBuddy on any device",
    "set.roadTeacher": "Parent / teacher view — assign work and track progress",
    "set.roadShare": "Share assignment sets with a friend",

    /* ---- errors ---- */
    "err.network": "Network error — check your connection.",
    "err.badKey": "That API key was rejected. Check it in Settings.",
    "err.serverNoKey": "The tutor server has no Claude key configured. Contact whoever runs this instance.",
    "err.rateLimited": "Rate limited by the API — wait a moment and try again.",
    "err.api": "API error {status}",
    "err.apiDetail": "API error {status}: {detail}",
    "err.tutorUnavailable": "Tutor unavailable (API {status}).",
    "err.pdfNoLib": "PDF reader failed to load. Refresh and try again.",
    "err.pdfNoText": "Couldn't find selectable text in that PDF. If it's a scan, upload it as a photo instead.",
    "err.imageType": "Please use a PNG, JPG, WEBP, or GIF image.",
    "err.imageSize": "That image is over 5 MB — try a smaller photo.",
    "err.readFile": "Could not read that file.",
    "err.zipNoLib": "ZIP reader failed to load. Refresh and try again.",
    "err.zipNoPdf": "No PDF found in that ZIP file.",
    "err.zipNoText": "Could not read text from the PDFs in that ZIP (they may be scanned pages).",

    "common.parent": "Parent / teacher",

    "sync.conflict": "Synced from another device — some local changes here were replaced.",

    "set.serverTitle": "Tutor server",
    "set.serverBody": "Question generation and live tutoring run on a small backend that holds the Claude key — nothing to configure here. Without it reachable, StudyBuddy runs in demo mode on the sample content.",
    "set.serverDown": "Not reachable — running in demo mode",
    "set.serverNoKey": "Connected, but no Claude key configured — running in demo mode",
    "set.serverLive": "Connected — live mode is on",
    "set.dataBodySynced": "Everything (assignments, attempts, progress) lives in this browser and syncs to your account.",
    "set.acctTitle": "Account",
    "set.acctSignedIn": "Signed in as {email}. Your library syncs to this account.",
    "set.acctSignedOut": "Not signed in — StudyBuddy works fully locally. Sign in to sync your library across devices.",
    "set.acctSignIn": "Sign in / create account",
    "set.acctSignOut": "Sign out",
    "set.acctSignedOutToast": "Signed out — local mode",
    "set.acctParentLink": "Parent / teacher linking",
    "set.acctNoServer": "The tutor server isn't reachable, so signing in won't work right now.",

    "session.nationalMixEmpty": "No imported sets for this subject yet.",
    "session.nationalMixTitle": "Mixed — {subject}",
    "session.nationalMixFallback": "National exam",
    "session.badgeNationalMix": "National exam",

    "create.optNational": "National exam",
    "create.optNationalSub": "Practise for the Swedish nationella prov",
    "create.pdfOrZipFile": "PDF or ZIP file",
    "create.zipExtracted": "Extracted text from {n} of {total} PDF files in “{name}”{audio}.",
    "create.zipSkippedAudio": " ({n} audio files skipped)",
    "create.npLevel": "Level",
    "create.npLevelPlaceholder": "Choose a level…",
    "create.npSubject": "Subject",
    "create.npSubjectPlaceholder": "Choose a subject…",
    "create.npPasteText": "Paste text",
    "create.npPastePlaceholder": "Paste an extract from the exam here (optional if you upload the file below)…",
    "create.npInfoExternal": "Opens a university page of past exams — download what you want to practise (PDF, ZIP, or whatever they offer), then upload or paste it here.",
    "create.npInfoLimited": "Real past exams in this subject contain copyrighted texts, so only sample tasks are freely published — the link shows those. Full historical exams have to be requested from Skolverket as a “begäran om allmän handling”.",
    "create.npGetMaterial": "Get exam material ↗",
    "create.npBadgeExample": "Samples",
    "create.npBadgeExternal": "External site",
    "create.npImportedOne": "{n} imported set for this subject:",
    "create.npImportedMany": "{n} imported sets for this subject:",
    "create.npMixLabel": "Mix all years — number of questions:",
    "create.npMixStart": "Start mix",
    "create.subjectLocked": "Locked to the national-exam subject",
    "create.preferFlashcards": "Prefer flashcards",

    "login.title": "Account",
    "login.intro": "Sign in to sync your library and progress across devices. Fully optional — StudyBuddy keeps working locally if you skip this.",
    "login.email": "Email",
    "login.password": "Password",
    "login.passwordHint": "At least 8 characters",
    "login.signIn": "Sign in",
    "login.createAccount": "Create account",
    "login.needAccount": "Need an account? Create one",
    "login.haveAccount": "Already have an account? Sign in",
    "login.signedInToast": "Signed in — syncing is on",
    "login.createdToast": "Account created — syncing is on",
    "login.serverDown": "The backend server isn't reachable right now — signing in won't work until it is.",
    "login.somethingWrong": "Something went wrong.",
    "login.back": "Back to settings",

    "parent.title": "Parent / teacher",
    "parent.signInPrompt": "Sign in to link accounts, assign work, and see progress.",
    "parent.backToMenu": "Back to menu",
    "parent.back": "Back",
    "parent.inviteHeading": "Invite a parent",
    "parent.inviteIntro": "Generate a code and share it with a parent or teacher so they can link to your account.",
    "parent.inviteGenerate": "Generate invite code",
    "parent.inviteShare": "Share this code — it expires in 30 minutes and works once.",
    "parent.studentsHeading": "Students you're linked to",
    "parent.studentsNone": "None yet — redeem a student's invite code below.",
    "parent.haveCode": "Have a student's invite code?",
    "parent.link": "Link",
    "parent.linkedToStudent": "Linked to {email}",
    "parent.assignSet": "Assign a set",
    "parent.assign": "Assign",
    "parent.noOwnSets": "You don't have any sets of your own to assign yet — make one from the menu first.",
    "parent.assigned": "Assigned “{title}” to {email}",
    "parent.unlink": "Unlink",
    "parent.unlinkConfirm": "Unlink {email}?",
    "parent.parentsHeading": "Parents / teachers linked to you",
    "parent.parentsNone": "No one yet. Generate a code above and share it with a parent or teacher.",
    "parent.assignedToYouHeading": "Assigned to you",
    "parent.assignedLoadFail": "Couldn't load assigned sets.",
    "parent.assignedNone": "Nothing waiting right now.",
    "parent.addToLibrary": "Add to my library",
    "parent.addedToLibrary": "Added “{title}” to your library",
    "parent.fromWho": "from {email}",
    "parent.studentProgressTitle": "Student progress",
    "parent.notAvailable": "Not available",
    "parent.noDataTitle": "No data yet",
    "parent.noDataBody": "This student hasn't synced anything yet.",
    "parent.studyStreak": "Study streak",
    "parent.streakDays": "{n} days",
    "parent.streakDay": "{n} day",
    "parent.daysSessions": "{days} day(s) studied · {sessions} session(s) completed",
    "parent.masteryHeading": "Mastery by subject",
    "parent.noMastery": "No mastery data yet.",
    "parent.dueHeading": "Due for review",
    "parent.dueCount": "{n} question(s) due.",
    "parent.dueNone": "Nothing due right now.",

    "common.undo": "Undo",

    "cal.prevMonth": "Previous month",
    "cal.nextMonth": "Next month",
    "cal.prevWeek": "Previous week",
    "cal.nextWeek": "Next week",
    "datepick.tomorrow": "Tomorrow",
    "datepick.in3days": "In 3 days",
    "datepick.nextMon": "Next Monday",
    "datepick.in1week": "In 1 week",
    "datepick.in2weeks": "In 2 weeks",

    "menu.goalToday": "{done} / {goal} today",
    "menu.goalDone": "Daily goal reached",
    "menu.goalSub": "Questions answered today",

    "prog.heatmapTitle": "Study days",
    "prog.heatmapSub": "The last 12 weeks — filled squares are days you studied.",

    "set.dailyGoal": "Daily goal (questions)",
    "set.dailyGoalNote": "The ring on the home screen and Progress fills as you answer questions each day. Set to 0 to hide it.",
    "set.dailyGoalUpdated": "Daily goal updated",

    "common.view": "View",

    "streak.freezeHelp": "Streak freezes — each one covers a single missed day. You earn one every 7-day streak, up to two.",
    "streak.freezeNext": "next freeze in {n} days",
    "streak.freezeUsedToast": "Streak freeze used — your {n}-day streak is safe",
    "streak.frozenDay": "streak freeze used",
    "streak.atRisk": "Study today to keep your {n}-day streak — a freeze is ready if you slip.",
    "streak.atRiskShort": "Streak at risk — study today",

    "prog.achievements": "Achievements",
    "prog.achProgress": "{have} / {need}",
    "prog.personalBest": "personal best: {n} days",

    "ach.multiToast": "{n} achievements unlocked!",
    "ach.streak3.title": "Getting started",
    "ach.streak3.desc": "A 3-day study streak.",
    "ach.streak7.title": "One week strong",
    "ach.streak7.desc": "A 7-day study streak.",
    "ach.streak30.title": "A month of momentum",
    "ach.streak30.desc": "A 30-day study streak.",
    "ach.streak100.title": "Unstoppable",
    "ach.streak100.desc": "A 100-day study streak.",

    "set.saved": "Saved",

    "q.confPrompt": "How sure were you?",
    "q.conf_guessed": "Guessed",
    "q.conf_unsure": "Unsure",
    "q.conf_knew": "Knew it",
    "q.workedNailed": "Nailed it",
    "q.workedRoughly": "Roughly right",
    "q.workedMissed": "Missed it",
    "q.blankAria": "Blank {n}",
    "q.clozeMissed": "Not quite. The missing word(s):",
    "q.tutorClozeWrong": "I filled in the blanks but I'm not sure they're right.",
    "q.mathKeypad": "Insert a maths symbol",

    "session.testBannerHints": "Test mode: one attempt per question. You can ask the tutor up to {n} times.",
    "session.adaptiveEase": "Let's slow down a little — the tutor's here, and the next few questions play to your strengths.",
    "session.adaptiveCruise": "You're cruising through these.",
    "session.adaptiveFinishNow": "Finish now",

    "tutor.hintsLeft": "{n} hints left in this test",
    "tutor.hintsGone": "No hints left in this test",

    "results.hintsUsedOne": "{n} hint used",
    "results.hintsUsedMany": "{n} hints used",

    "set.studying": "Studying",
    "set.testHints": "Hints during a test",
    "set.testHints0": "None — tutor off",
    "set.testHints1": "1 hint",
    "set.testHints2": "2 hints",
    "set.testHints3": "3 hints",
    "set.testHintsNote": "How many times the tutor will answer during a test before it locks. None keeps a test a pure test.",
    "set.adaptive": "Adaptive practice",
    "set.adaptiveOn": "On",
    "set.adaptiveOff": "Off",
    "set.adaptiveNote": "A practice session reacts to how it's going — opening the tutor if you're struggling, or offering an early finish if you're breezing through.",

    "ed.kindCloze": "Fill in the blank",
    "ed.clozeHint": "Write the sentence and wrap each missing word in double braces, e.g. The capital of France is {{Paris}}. Separate alternatives with a pipe: {{Paris|paris}}.",
    "ed.clozeCount": "{n} blank(s)",

    "prog.achCount": "{have} of {need} unlocked",

    "ach.q50.title": "Warming up",
    "ach.q50.desc": "Answered 50 questions.",
    "ach.q250.title": "Well read",
    "ach.q250.desc": "Answered 250 questions.",
    "ach.q1000.title": "Scholar",
    "ach.q1000.desc": "Answered 1,000 questions.",
    "ach.subj80.title": "Subject strong",
    "ach.subj80.desc": "Took a subject to 80% mastery.",
    "ach.subj100.title": "Mastered",
    "ach.subj100.desc": "Took a subject to 100% mastery.",
    "ach.all60.title": "Well rounded",
    "ach.all60.desc": "Every subject you've studied is at 60%+.",
    "ach.goalweek.title": "In the habit",
    "ach.goalweek.desc": "Hit your daily goal 7 days running.",
    "ach.subj3.title": "Broadening out",
    "ach.subj3.desc": "Studied 3 different subjects.",
    "ach.subj5.title": "Polymath",
    "ach.subj5.desc": "Studied 5 different subjects.",
    "ach.firstreview.title": "Coming back to it",
    "ach.firstreview.desc": "Finished a review session.",
    "ach.firstfreeze.title": "Saved by the shield",
    "ach.firstfreeze.desc": "Used a streak freeze.",

    "session.pomoTitle": "Focus timer",
    "session.pomoDone": "Time for a break — nice focus.",

    "recap.title": "Last week",
    "recap.daysOne": "{n} day studied",
    "recap.daysMany": "{n} days studied",
    "recap.qOne": "{n} question",
    "recap.qMany": "{n} questions",
    "recap.topicsOne": "{n} topic improved",
    "recap.topicsMany": "{n} topics improved",
    "recap.strongest": "{subject} is your strongest",

    "set.pomodoro": "Focus timer",
    "set.pomodoroOff": "Off",
    "set.pomodoro25": "25 minutes",
    "set.pomodoro50": "50 minutes",
    "set.pomodoroNote": "Shows a countdown in a study session and chimes gently when the time's up.",

    "set.font": "Typeface",
    "set.fontSystem": "Default",
    "set.fontHyperlegible": "Hyperlegible",
    "set.textSize": "Text size",
    "set.textSizeS": "Small",
    "set.textSizeM": "Medium",
    "set.textSizeL": "Large",

    "ed.dragReorder": "Drag to reorder",
    "ed.moveUp": "Move question {n} up",
    "ed.moveDown": "Move question {n} down",

    "menu.itemPrint": "Print worksheet",

    "print.action": "Print / Save PDF",
    "print.name": "Name",
    "print.date": "Date",
    "print.answerKey": "Answer key",

    "gallery.title": "Sample sets",
    "gallery.intro": "Ready-made sets you can try before building your own. Adding one drops it into your library like any other.",
    "gallery.add": "Add to library",
    "gallery.inLibrary": "In your library",
    "gallery.added": "Added “{title}”",
    "gallery.questions": "{n} questions",

    "onb.s1title": "Study your own material",
    "onb.s1body": "Paste notes, upload a PDF or photo, or just name a topic — StudyBuddy turns it into a set of questions.",
    "onb.s2title": "A tutor that asks, not tells",
    "onb.s2body": "Work through questions one at a time. Stuck? The tutor gives hints, never the answer — until you've had a real go.",
    "onb.s3title": "Review brings it back",
    "onb.s3body": "Questions you got wrong come back on a schedule, so things actually stick. Your streak and progress track it all.",
    "onb.next": "Next",
    "onb.browse": "Browse sample sets",
    "onb.makeFirst": "Make my first set",

    "cmd.placeholder": "Jump to a set or an action…",
    "cmd.openSet": "Open set",
    "cmd.action": "Action",
    "cmd.review": "Review today",
    "cmd.weak": "Practise weak spots",
    "cmd.new": "New set",
    "cmd.gallery": "Sample sets",
    "cmd.progress": "Progress",
    "cmd.settings": "Settings",
    "cmd.lang": "Switch to {lang}",
    "cmd.theme": "Toggle dark mode",

    "create.optImport": "Import cards",
    "create.optImportSub": "Quizlet / Anki / CSV export",
    "create.takePhoto": "Take a photo",
    "create.choosePhoto": "Choose a file",
    "create.importPlaceholder": "term<tab>definition, one per line — or paste a Quizlet export here",
    "create.importHint": "Paste exported cards or upload a .csv. Term and definition can be split by a tab, comma, or \" - \".",
    "create.importPaste": "Paste cards",
    "create.importFile": "Or upload a file",
    "create.importFound": "Found {n} cards",
    "create.importNone": "Couldn't find any term / definition pairs.",
    "create.importBuild": "Build the set",

    "create.optBlank": "Build it myself",
    "create.optBlankSub": "A blank set to fill in — no AI",
    "create.blankHint": "Starts you off with a few editable questions of each kind. Handy for trying the app out.",
    "create.blankBuild": "Create blank set",
    "create.blankTitle": "Untitled set",
    "create.blankQ": "Sample question {n} — edit me",
    "create.blankCloze": "Sample {n}: the capital of France is {{Paris}}",
    "create.subjectPlaceholder": "New subject, or pick one below",
    "create.subjectExisting": "Existing subjects",

    "create.needKeyShort": "Add a Claude key in Settings to use this",
    "create.splitFound": "Looks like {n} sections in here.",
    "create.splitEach": "Make a set for each ({n})",
    "create.splitTitle": "Building your sets",
    "create.splitSub": "One set per section — this takes a moment each.",
    "create.splitDone": "Made {n} sets",

    "tutor.voiceStart": "Speak to the tutor",
    "tutor.voiceStop": "Stop listening",
    "tutor.voiceListening": "Listening…",
    "tutor.voiceListenUnsupported": "This browser can't do voice input",
    "tutor.explainWhyLabel": "Explain why my answer was wrong",
    "tutor.explainWhyPrompt": "I answered {answer} and it was wrong. Explain why, and what the right idea is — don't just restate the answer.",
    "tutor.explainWhyBlank": "nothing",
    "tutor.explainWhyScripted": "Let's look at where that went sideways. Compare your answer to the model answer above — which part doesn't match, and why?",

    "q.explainWhy": "Explain why",

    "set.voice": "Tutor voice",
    "set.voiceOn": "Read replies aloud",
    "set.voiceOff": "Off",
    "set.voiceNote": "When on, the tutor speaks its replies. The mic button lets you answer out loud.",
    "set.voiceUnsupported": "This browser doesn't support speech, so voice is unavailable.",

    "edit.moreLike": "Add more like these",
    "edit.moreWorking": "Writing more questions…",
    "edit.moreAdded": "Added {n} new questions — review them below.",
    "edit.moreFailed": "Couldn't add more just now. Try again in a moment.",

    "menu.itemMore": "Add more questions",

    "teach.title": "Teach it back",
    "teach.intro": "Explain {subject} in your own words. Best way to know you've really got it.",
    "teach.tile": "Teach it back",
    "teach.round": "Round {n} of {total}",
    "teach.ask": "Explain “{topic}” in your own words.",
    "teach.placeholder": "Explain it as if to a classmate…",
    "teach.answerAria": "Your explanation",
    "teach.submit": "Check my explanation",
    "teach.checking": "Reading it…",
    "teach.next": "Next topic",
    "teach.finish": "See how I did",
    "teach.gradePrompt": "Student was asked to explain “{topic}” in their own words.",
    "teach.rubric": "Full credit for a clear, correct explanation that shows real understanding — wording doesn't matter.",
    "teach.demoOk": "That's a solid explanation — you've clearly got the idea.",
    "teach.demoThin": "Good start, but stretch it further — say more about how and why it works.",
    "teach.doneTitle": "Nice work",
    "teach.doneBody": "You explained {correct} of {total} clearly. That's the stuff that sticks.",
    "teach.toProgress": "Back to progress",
    "teach.attemptTitle": "Taught back: {subject}",
    "teach.goneTitle": "Nothing to teach back yet",
    "teach.goneBody": "Study a subject up to 80% mastery and it'll show up here.",

    "nav.home": "Home",
    "nav.study": "Study",
    "nav.calendar": "Calendar",
    "nav.library": "Library",
    "nav.create": "Create",
    "nav.leaveConfirm": "Leave this session?\n\nYour progress is saved — you'll come back to exactly where you left off.",
    "nav.leave": "Leave",
    "nav.stay": "Stay",
    "common.confirm": "Confirm",
    "common.menu": "Menu",
    "menu.studyTitle": "Study",
    "menu.studySub": "Every assignment and test in your library.",
    "menu.calendarTitle": "Calendar",
    "menu.calendarSub": "Every assignment and test with a due date.",
    "menu.calendarNone": "Nothing has a due date yet — set one from a set's ⋮ menu, or when you create it.",

    "session.testOff": "Turn off test mode",
    "session.testOn": "Turn test mode back on",
    "session.testOffConfirm": "Turn off test mode?\n\nYou'll get the tutor and a second try on each question, and this won't be saved as a test result.",
    "session.testOffToast": "Test mode off — the tutor's here to help.",
    "session.testOnToast": "Test mode back on.",
    "session.testModeOff": "Test mode is off for this run.",

    "session.examBanner": "Exam mode — a countdown, one attempt per question, no hints. The tutor goes through everything with you afterwards.",
    "session.examBadge": "Exam mode",
    "session.examTimeUp": "Time's up — your answers were submitted automatically.",

    "common.library": "Practice library",
    "lib.title": "Practice library",
    "lib.loadFail": "Couldn't load the library",
    "lib.loadFailBody": "Try again in a moment.",
    "lib.search": "Search the library — subject, course or set…",
    "lib.searchAria": "Search the practice library",
    "lib.intro": "Ready-made exercises you can start on right away — no upload needed. Pick a level to see subjects.",
    "lib.pickSubject": "{level} — which subject?",
    "lib.noHits": "No results for “{q}”. Try a subject, a course or a school year.",
    "lib.hitsOne": "{n} result",
    "lib.hitsMany": "{n} results",
    "lib.add": "Add",
    "lib.study": "Study",
    "lib.exam": "Exam mode",
    "lib.examTip": "Exam mode: a countdown, no hints, and the answer key only after you finish.",
    "lib.added": "“{title}” added",
    "lib.addFail": "Couldn't add that set",
    "lib.addAll": "Add all ({n})",
    "lib.addedN": "Added {n} sets",
    "lib.allThere": "Everything was already in your library",
    "lib.allAdded": "All sets added ✓",
    "lib.examLenLabel": "Time limit",
    "lib.examLenNone": "No limit (count up)",
    "lib.examStart": "Start exam",

    "menu.libraryCta": "Browse the practice library",
    "menu.libraryLink": "Practice library",

    "results.examSuffix": " · exam mode",
    "results.examLimit": " (limit {n} min)",
    "results.timedOut": "Time ran out — this was submitted automatically.",
  },

  /* ================================================================ */
  sv: {
    /* ---- common ---- */
    "common.appName": "StudyBuddy",
    "common.back": "Tillbaka",
    "common.backToMenu": "Tillbaka till menyn",
    "common.cancel": "Avbryt",
    "common.save": "Spara",
    "common.close": "Stäng",
    "common.delete": "Ta bort",
    "common.loading": "Laddar…",
    "common.progress": "Framsteg",
    "common.settings": "Inställningar",
    "common.newSet": "Nytt set",
    "common.assignment": "Uppgift",
    "common.test": "Prov",
    "common.assignments": "Uppgifter",
    "common.tests": "Prov",
    "common.assignmentsLower": "uppgifter",
    "common.testsLower": "prov",
    "common.general": "Allmänt",
    "common.somethingWrong": "Något gick fel",
    "common.somethingWrongShort": "Något gick fel.",
    "common.questionOne": "{n} fråga",
    "common.questionMany": "{n} frågor",
    "common.language": "Språk",

    /* ---- dates ---- */
    "date.today": "Idag",
    "date.tomorrow": "Imorgon",
    "date.inDays": "om {n} dagar",
    "date.inWeekOne": "om 1 vecka",
    "date.inWeeks": "om {n} veckor",
    "date.inMonthOne": "om 1 månad",
    "date.inMonths": "om {n} månader",
    "date.overdueOne": "1 dag försenad",
    "date.overdueMany": "{n} dagar försenad",
    "date.dueNow": "dags nu",

    /* ---- menu ---- */
    "menu.title": "Meny",
    "menu.morning": "God morgon",
    "menu.afternoon": "God eftermiddag",
    "menu.evening": "God kväll",
    "menu.subHasKey": "Välj något att plugga på, eller skapa ett nytt set.",
    "menu.subNoKey": "Kör i demoläge — anslut handledarservern för live-generering och handledning.",
    "menu.studyTitle": "Studera",
    "menu.studySub": "Alla uppgifter och prov i ditt bibliotek.",
    "menu.calendarTitle": "Kalender",
    "menu.calendarSub": "Alla uppgifter och prov med ett datum.",
    "menu.calendarNone": "Inget har ett datum ännu — lägg till ett via ett sets ⋮-meny, eller när du skapar det.",
    "menu.searchPlaceholder": "Sök bland set…",
    "menu.searchAria": "Sök bland dina set",
    "menu.sortAria": "Sortera set",
    "menu.sortRecent": "Senast tillagda",
    "menu.sortName": "Namn (A–Ö)",
    "menu.sortWeakest": "Svagast först",
    "menu.chipAll": "Alla",
    "menu.addSubject": "Lägg till ämne",
    "menu.addSubjectPh": "Ämnesnamn",
    "menu.subjectAdded": "La till ”{name}” — välj det när du skapar ett set",
    "menu.newAssignment": "Ny uppgift",
    "menu.newTest": "Nytt prov",
    "menu.inProgress": "Påbörjad",
    "menu.answeredOf": "{n} av {total} besvarade",
    "menu.doneTimes": " · gjord {n} ggr",
    "menu.cardAria": "{title}, {subject}, {count} frågor",
    "menu.cardAriaOpen": "{title}, {subject}, {count} frågor, påbörjad",
    "menu.cardOptions": "Alternativ för {title}",
    "menu.masteryTitle": "{pct}% kunskapsnivå — hur bra det gått på det här settets områden",
    "menu.emptyFirstTitle": "Ditt bibliotek är tomt",
    "menu.emptyFirstBody": "Skapa ett set av dina egna anteckningar, en PDF, ett foto eller bara ett ämne — eller ladda demo-seten för att se hur det funkar.",
    "menu.emptyAssignTitle": "Inga uppgifter än",
    "menu.emptyAssignBody": "Skapa en av dina anteckningar, en PDF, ett foto eller bara ett ämne.",
    "menu.emptyTestTitle": "Inga prov än",
    "menu.emptyTestBody": "Skapa ett på samma sätt — markera det bara som prov.",
    "menu.tryDemo": "Testa en demo",
    "menu.demoAdded": "Demo-set tillagda",
    "menu.demoFailed": "Kunde inte ladda demo-seten",
    "menu.noMatch": "Inga {kind} matchar ”{q}”. ",
    "menu.switchToTests": "{n} träffar under Prov — byt dit",
    "menu.switchToAssignments": "{n} träffar under Uppgifter — byt dit",
    "menu.itemRename": "Byt namn",
    "menu.itemEdit": "Redigera frågor",
    "menu.itemDuplicate": "Duplicera",
    "menu.itemDelete": "Ta bort",
    "menu.itemDue": "Deadline",
    "menu.renamePrompt": "Byt namn på settet:",
    "menu.renameEmpty": "Settet behöver ett namn",
    "menu.renamed": "Namnet ändrat",
    "menu.copiedAs": "Kopierad som ”{title}”",
    "menu.deleteConfirm": "Ta bort ”{title}”?\n\nDet går inte att ångra.",
    "menu.deleteConfirmAttempts": "Ta bort ”{title}”?\n\nDet tar också bort {n} sparade försök ur din historik.\n\nDet går inte att ångra.",
    "menu.deleted": "Borttagen",
    "menu.tileDue": "{n} att repetera",
    "menu.tileDueSub": "Repetera från alla set",
    "menu.tileContinue": "Fortsätt",
    "menu.tileContinueSub": "{title} · {n} av {total} besvarade",
    "menu.tileStreakOne": "{n} dag i rad",
    "menu.tileStreak": "{n} dagar i rad",
    "menu.tileStreakSub": "Se dina framsteg",
    "menu.tileWeak": "Svaga punkter",
    "menu.tileWeakSub": "Öva på det du ofta missar",
    "menu.upcoming": "Kommande",
    "menu.upcomingStudy": "Plugga",
    "menu.upcomingStudyAria": "Plugga {title} nu",
    "menu.upcomingAll": "Visa alla ({n})",
    "menu.upcomingLess": "Visa färre",
    "menu.calendarShowMonth": "Hela månaden",
    "menu.calendarShowWeek": "Denna vecka",
    "menu.calendarEmptyWeek": "Inget att göra denna vecka.",
    "menu.nextTestToday": "Nästa prov är idag",
    "menu.nextTestTomorrow": "Nästa prov är imorgon",
    "menu.nextTestIn": "Nästa prov om {n} dagar",
    "menu.nextTestOverdue": "Nästa prov är försenat",
    "menu.upcomingCount": "Kommande ({n})",
    "menu.dueLabel": "Deadline {date}",
    "menu.panelToday": "Idag",
    "menu.panelSets": "Dina set",
    "menu.filter": "Filter",
    "menu.resumeGo": "Fortsätt",
    "menu.achAllDone": "Alla utmärkelser upplåsta — snyggt jobbat. 🎉",

    /* ---- due date dialog ---- */
    "due.title": "Deadline",
    "due.body": "När ska ”{title}” vara klar?",
    "due.field": "Datum",
    "due.save": "Spara datum",
    "due.clear": "Ta bort datum",
    "due.saved": "Deadline satt",
    "due.cleared": "Deadline borttagen",
    "due.invalid": "Välj ett giltigt datum",

    /* ---- session ---- */
    "session.questionOf": "Fråga {n} av {total} · {done} besvarade",
    "session.skippedSuffix": " · {n} överhoppade",
    "session.next": "Nästa",
    "session.finish": "Slutför",
    "session.skip": "Hoppa över",
    "session.exit": "Lämna",
    "session.exitConfirm": "Lämna passet?\n\nDina framsteg sparas — du kan fortsätta där du slutade.",
    "session.resumeTitle": "Fortsätta där du slutade?",
    "session.resumeRemaining": "Du svarade på {n} av {total} förra gången — {left} kvar.",
    "session.resumeDone": "Du svarade på {n} av {total} förra gången, så du är redo att slutföra.",
    "session.continue": "Fortsätt",
    "session.startOver": "Börja om",
    "session.testBanner": "Provläge: ett försök per fråga och inga tips. Handledaren går igenom allt med dig efteråt.",
    "session.badgeReview": "Repetition",
    "session.badgePractice": "Övning",
    "session.badgeWeak": "Svaga punkter",
    "session.reviewTitle": "Repetitionspass",
    "session.reviewMore": "{n} till väntar — kom tillbaka efter den här omgången.",
    "session.practiceTitle": "Övning",
    "session.weakTitle": "Svaga punkter",
    "session.notFoundTitle": "Inget att plugga på här",
    "session.goneSet": "Det settet finns inte längre.",
    "session.emptySet": "Det settet har inga frågor än.",
    "session.goneQuestions": "De här frågorna finns inte längre.",
    "session.goneResult": "Det resultatet finns inte längre.",
    "session.nothingDueTitle": "Inget att repetera just nu",
    "session.nothingDueBody": "Repetition tar tillbaka frågor precis innan du hinner glömma dem. Kom tillbaka imorgon, eller plugga ett set för att lägga till fler.",
    "session.nothingPractiseTitle": "Inget att öva på",
    "session.nothingPractiseBody": "Du hade allt rätt i det passet.",
    "session.noWeakTitle": "Inga svaga punkter än",
    "session.noWeakBody": "Gör några pass först — sedan övar det här på det du ofta svarar fel på.",
    "session.annCorrect": "Rätt.",
    "session.annWrong": "Fel. Handledaren kan hjälpa.",
    "session.annRecorded": "Svaret sparat.",
    "session.annSkipped": "Överhoppad. Du får se den igen på slutet.",
    "session.annQuestion": "Fråga {n} av {total}.",
    "session.needHint": "Behöver du ett tips?",
    "session.hideTutor": "Dölj handledaren",
    "session.shortcutsBtn": "Kortkommandon",
    "session.shortcutTip": "Tips: tryck på ? för kortkommandon",

    /* ---- shortcuts sheet ---- */
    "keys.title": "Kortkommandon",
    "keys.pick": "Välj ett svarsalternativ",
    "keys.enter": "Rätta ditt svar, gå sedan vidare",
    "keys.next": "Nästa fråga",
    "keys.skip": "Hoppa över",
    "keys.space": "Vänd ett minneskort",
    "keys.show": "Visa den här listan",
    "keys.close": "Stäng",

    /* ---- questions ---- */
    "q.check": "Rätta svaret",
    "q.submit": "Skicka svar",
    "q.checking": "Rättar…",
    "q.submitting": "Skickar…",
    "q.recorded": "Svaret sparat.",
    "q.leftBlank": "Lämnat tomt.",
    "q.correct": "Rätt!",
    "q.notQuite": "Inte riktigt — försök igen.",
    "q.stillNotRight": "Fortfarande fel. Läs handledarens tips och välj igen — eller visa svaret nedan.",
    "q.reveal": "Visa svaret & fortsätt",
    "q.answerIs": "Rätt svar är {letter}.",
    "q.typeAnswer": "Skriv ditt svar…",
    "q.yourAnswer": "Ditt svar",
    "q.modelAnswer": "Exempelsvar:",
    "q.fullSolution": "Fullständig lösning:",
    "q.disagree": "Håller du inte med om rättningen? ",
    "q.appeal": "Jag tycker att mitt svar var rätt",
    "q.appealDone": "Markerat som rätt. Titta ändå på exempelsvaret — det är lätt att missa en bit.",
    "q.heuristicOk": "Det täcker huvudpoängerna — kolla detaljerna nedan.",
    "q.heuristicMiss": "Det här verkar sakna några av huvudpoängerna. Jämför med exempelsvaret nedan.",
    "q.flipAria": "Vänd kortet",
    "q.tapFlip": "Tryck på kortet för att vända, eller tryck på mellanslag.",
    "q.flashcardRecallPlaceholder": "Skriv vad du minns från kortets baksida…",
    "q.gradingFailed": "Kunde inte rätta det här automatiskt — här är exempelsvaret att jämföra med.",
    "q.rateAgain": "Igen",
    "q.rateHard": "Svårt",
    "q.rateGood": "Bra",
    "q.rateEasy": "Lätt",
    "q.workedPlaceholder": "Räkna ut det här — handledaren till höger hjälper till.",
    "q.workedPlaceholderTest": "Räkna ut det här.",
    "q.yourWorking": "Dina uträkningar",
    "q.showStep": "Visa ett steg",
    "q.doneShowAnswer": "Jag är klar — visa svaret",
    "q.reasoningGetThere": "Kom ditt resonemang fram?",
    "q.yesHadIt": "Ja, jag hade rätt",
    "q.notQuiteBtn": "Inte riktigt",
    "q.tutorRight": "Jag valde rätt!",
    "q.tutorWrongMc": "Jag valde ”{choice}” och det var fel. Kan du hjälpa mig förstå varför?",
    "q.tutorGotIt": "Jag tror jag fick den rätt.",
    "q.tutorWhatMissing": "Så här skrev jag: ”{answer}”. Vad missar jag?",
    "q.tutorForgot": "Jag kom inte ihåg den här. Kan du hjälpa mig komma ihåg den?",
    "q.tutorRemembered": "Jag kom ihåg den!",
    "q.tutorRevealedStep": "Jag har visat steg {n}. Kan du knuffa mig mot nästa del?",

    /* ---- tutor ---- */
    "tutor.name": "StudyBuddy",
    "tutor.subLive": "din handledare",
    "tutor.subDemo": "din handledare · demoläge",
    "tutor.subLocked": "avstängd under provet",
    "tutor.lockedTitle": "Jag sitter över den här.",
    "tutor.lockedBody": "Det är ett prov, så inga tips — svara så gott du kan. När du är klar går jag igenom allt du missade med dig.",
    "tutor.ask": "Fråga handledaren…",
    "tutor.askAria": "Skriv till handledaren",
    "tutor.send": "Skicka",
    "tutor.convAria": "Samtal med handledaren",
    "tutor.voiceAria": "Röstläge — kommer snart",
    "tutor.voiceSoon": "snart",
    "tutor.voiceToast": "Röstläge är på väg — du kommer kunna prata igenom uppgifter högt.",
    "tutor.prefix": "Handledaren: {text}",
    "tutor.snag": "Handledaren fick problem. Försök igen om en stund.",
    "tutor.firstThought": "Nu tar vi den här. Vad är din första tanke?",
    "tutor.scriptedCorrect": "Precis rätt — snyggt!",
    "tutor.scriptedEncourage": "Testa en gång till — du är nära.",

    /* ---- results ---- */
    "results.title": "Resultat",
    "results.great": "Snyggt jobbat! 🎉",
    "results.nice": "Bra kämpat 💪",
    "results.none": "Inga resultat att visa",
    "results.correctOf": "{c} / {n} rätt",
    "results.testSuffix": " · prov",
    "results.tookSec": "Tog {n} s",
    "results.tookMin": "Tog {n} min",
    "results.tookHour": "Tog {h} h {m} min",
    "results.topicMastery": "Kunskapsnivå per område",
    "results.worthLook": "Värt att titta på igen",
    "results.correctAnswerLabel": "Rätt svar:",
    "results.practiseTheseOne": "Öva på den nu",
    "results.practiseTheseMany": "Öva på de {n} nu",
    "results.tutorSatOut": "Handledaren satt över provet — nu går den igenom de här med dig.",
    "results.tryAgain": "Försök igen",
    "results.reviewAgain": "Repetera igen",
    "results.seeProgress": "Se framsteg",

    /* ---- progress ---- */
    "prog.title": "Dina framsteg",
    "prog.streak": "Pluggstreak",
    "prog.streakDaysOne": "{n} dag",
    "prog.streakDaysMany": "{n} dagar",
    "prog.streakAria": "Pluggat {n} av de senaste 14 dagarna",
    "prog.summary": "{days} pluggade · {sessions} genomförda",
    "prog.daysOne": "1 dag",
    "prog.daysMany": "{n} dagar",
    "prog.sessionsOne": "1 pass",
    "prog.sessionsMany": "{n} pass",
    "prog.mastery": "Kunskapsnivå per ämne",
    "prog.masteryEmpty": "Gör klart ett pass för att börja bygga kunskapsnivåer. Svagaste området visas först.",
    "prog.masteryAria": "{subject}: {pct}% kunskapsnivå",
    "prog.practiseWeak": "Öva svaga punkter",
    "prog.due": "Att repetera",
    "prog.dueCount": "Att repetera ({n})",
    "prog.reviewToday": "Repetera idag",
    "prog.reviewExplain": "”Repetera idag” övar bara på de här frågorna, hämtade från alla dina set.",
    "prog.nothingDue": "Inget att repetera just nu. Repetition tar tillbaka frågor precis innan du hinner glömma dem.",
    "prog.moreDue": "+ {n} till",

    /* ---- create ---- */
    "create.title": "Nytt pluggset",
    "create.stepSource": "Källa",
    "create.stepMaterial": "Material",
    "create.stepReview": "Granska",
    "create.whereFrom": "Var ska frågorna komma ifrån?",
    "create.optPaste": "Klistra in text",
    "create.optPasteSub": "Anteckningar, en artikel, ett kapitel",
    "create.optPdf": "Ladda upp PDF",
    "create.optPdfSub": "Ett arbetsblad eller en boksida",
    "create.optPhoto": "Ladda upp foto",
    "create.optPhotoSub": "En bild på en sida eller tavla",
    "create.needKey": "Att skapa frågor kräver handledarservern. ",
    "create.needKeyLink": "Se dess status i Inställningar",
    "create.needKeyTail": " — eller testa demo-seten på menyn så länge.",
    "create.material": "Studiematerial",
    "create.materialPlaceholder": "Klistra in dina anteckningar eller din text här…",
    "create.pdfFile": "PDF-fil",
    "create.photo": "Foto",
    "create.reading": "Läser…",
    "create.extracted": "Hämtade {n} tecken från ”{name}”.",
    "create.loadedFile": "Laddade ”{name}”.",
    "create.readFail": "Kunde inte läsa filen.",
    "create.subject": "Ämne",
    "create.type": "Typ",
    "create.typeAssignment": "Uppgift (övning)",
    "create.typeTest": "Prov (quiz)",
    "create.howMany": "Hur många frågor",
    "create.generate": "Skapa frågor",
    "create.generating": "Skriver dina frågor…",
    "create.generatingSub": "Det tar oftast 10–30 sekunder.",
    "create.needMaterial": "Lägg till lite material eller ett ämne först.",
    "create.genFailed": "Det gick inte att skapa frågorna. Försök igen eller förenkla materialet.",
    "create.setTitle": "Titel",
    "create.setTitleAria": "Settets titel",
    "create.countNote": "{n} · ändra vad du vill nedan och spara sedan.",
    "create.addQuestion": "+ fråga",
    "create.saveSet": "Spara set",
    "create.addAtLeastOne": "Lägg till minst en fråga.",
    "create.giveName": "Ge settet ett namn.",
    "create.saved": "Sparat!",
    "create.dueDate": "Deadline (valfritt)",

    /* ---- edit ---- */
    "edit.title": "Redigera set",
    "edit.pageTitle": "Redigera — {title}",
    "edit.gone": "Det settet finns inte längre",
    "edit.saveChanges": "Spara ändringar",
    "edit.saved": "Sparat",
    "edit.giveName": "Ge settet ett namn",
    "edit.needQuestion": "Settet behöver minst en fråga",
    "edit.dueDate": "Deadline",

    /* ---- question editor ---- */
    "ed.none": "Inga frågor än — lägg till en nedan.",
    "ed.qBadge": "F{n}",
    "ed.qTextAria": "Text för fråga {n}",
    "ed.question": "Fråga",
    "ed.type": "Frågetyp",
    "ed.kindMc": "Flervalsfråga",
    "ed.kindText": "Kort svar",
    "ed.kindFlash": "Minneskort",
    "ed.kindWorked": "Steg-för-steg-uppgift",
    "ed.topicPlaceholder": "område",
    "ed.topicAria": "Områdesetikett",
    "ed.choiceCorrect": "Alternativ {letter} är rätt",
    "ed.choiceAria": "Alternativ {letter}",
    "ed.removeChoice": "Ta bort alternativ {letter}",
    "ed.selectCorrect": "Markera radioknappen bredvid det rätta alternativet.",
    "ed.addChoice": "+ alternativ",
    "ed.backOfCard": "Kortets baksida",
    "ed.modelAnswer": "Exempelsvar",
    "ed.answerAria": "Svar",
    "ed.deleteQuestion": "Ta bort fråga {n}",
    "ed.deleteQuestionTitle": "Ta bort fråga",

    /* ---- settings ---- */
    "set.title": "Inställningar",
    "set.lookFeel": "Utseende & ljud",
    "set.aiTitle": "AI",
    "set.theme": "Tema",
    "set.themeSystem": "Följ min enhet",
    "set.themeLight": "Ljust",
    "set.themeDark": "Mörkt",
    "set.themeUpdated": "Tema uppdaterat",
    "set.language": "Språk",
    "set.languageNote": "Byter språk i gränssnittet och ber handledaren svara på det språket. Demoseten följer med; dina egna set behåller språket de skapades på.",
    "set.langUpdated": "Språk uppdaterat",
    "set.sound": "Ljudeffekter",
    "set.soundNote": "En mjuk ton för rätt och fel svar, och en liten fanfar vid ett bra resultat.",
    "set.soundOn": "På",
    "set.soundOff": "Av",
    "set.soundUpdated": "Ljud uppdaterat",
    "set.keyTitle": "Claude API-nyckel",
    "set.keyBody": "Behövs för att skapa uppgifter av ditt material och för live-handledning. Utan den kör StudyBuddy i demoläge på exempelinnehållet.",
    "set.key": "Nyckel",
    "set.show": "Visa",
    "set.hide": "Dölj",
    "set.save": "Spara",
    "set.keySaved": "Nyckel sparad — live-handledning är på",
    "set.keyCleared": "Nyckel borttagen — demoläge",
    "set.keyWarning": " Din nyckel sparas bara i den här webbläsaren (localStorage). Det är okej för personligt bruk. Lägg inte appen på en offentlig webbplats förrän en liten server håller nyckeln i stället — annars kan vem som helst som besöker den använda din nyckel.",
    "set.getKeyAt": "Hämta en nyckel på ",
    "set.billed": ". Användningen faktureras ditt Anthropic-konto.",
    "set.modelTitle": "Modell & handledare",
    "set.modelIntro": "StudyBuddy använder olika Claude-modeller för olika jobb, så du inte betalar toppris för att rätta ett enradssvar.",
    "set.qualityCost": "Kvalitet & kostnad",
    "set.presetUpdated": "Modellval uppdaterat",
    "preset.balanced": "Balanserat — rekommenderas",
    "preset.balancedHint": "Bästa modellen skriver dina frågor; en lättare rättar svaren. Bra kvalitet, mycket lägre kostnad.",
    "preset.best": "Bästa kvalitet",
    "preset.bestHint": "Claude Opus 5 till allt. Bästa handledningen, och den dyraste.",
    "preset.cheapest": "Lägsta kostnad",
    "preset.cheapestHint": "Snabbt och billigt hela vägen. Bra för att nöta fakta; svagare på att förklara svåra idéer.",
    "set.jobWriting": "Skriva ett set",
    "set.jobTutoring": "Handleda dig",
    "set.jobMarking": "Rätta svar",
    "set.whenPerSet": "en gång per set",
    "set.whenEveryMsg": "varje meddelande",
    "set.whenEveryAnswer": "varje skrivet svar",
    "set.replyLength": "Handledarens svarslängd",
    "set.verbConcise": "Kortfattat — korta tips",
    "set.verbNormal": "Normal (standard)",
    "set.verbDetailed": "Utförligt — fylligare förklaringar",
    "set.tutorStyleUpdated": "Handledarstil uppdaterad",
    "set.demoTitle": "Demoinnehåll",
    "set.demoNone": "Två färdiga set (Fotosyntes – grunderna, Antikens Rom) som du kan testa utan API-nyckel — handledaren funkar i demoläge också.",
    "set.demoPartial": "{loaded} av {total} demo-set finns i ditt bibliotek. Du kan lägga tillbaka det som saknas, eller rensa bort dem.",
    "set.demoAll": "Båda demo-seten finns i ditt bibliotek. De fungerar som vilket set som helst — plugga, redigera eller ta bort dem.",
    "set.demoLoad": "Ladda demo-set",
    "set.demoAddMissing": "Lägg tillbaka det som saknas",
    "set.demoRemove": "Ta bort demo-set",
    "set.demoRemoveConfirm": "Ta bort demo-seten ur ditt bibliotek?\n\nFörsök du gjort på dem finns kvar i historiken.",
    "set.demoRemoved": "Demo-set borttagna",
    "set.demoAddedOne": "1 demo-set tillagt",
    "set.demoAddedMany": "{n} demo-set tillagda",
    "set.demoAlready": "Finns redan i ditt bibliotek",
    "set.demoFailed": "Kunde inte ladda demo-seten",
    "set.dataTitle": "Dina data",
    "set.dataBody": "Allt (uppgifter, försök, framsteg) ligger i den här webbläsaren.",
    "set.export": "Exportera JSON",
    "set.wipe": "Radera all data",
    "set.wipeConfirm": "Radera alla set, försök och framsteg?\n\nDet går inte att ångra. Exportera en säkerhetskopia först om du vill behålla dem.",
    "set.wiped": "Data raderad",
    "set.backupDownloaded": "Säkerhetskopia nedladdad",
    "set.import": "Importera",
    "set.importConfirm": "Det här ersätter allt som finns i appen just nu med filen du valde.\n\nExportera en säkerhetskopia först om du vill behålla det som finns nu.",
    "set.imported": "Data importerad.",
    "set.importBadFile": "Den filen kunde inte läsas som en StudyBuddy-säkerhetskopia.",
    "set.importReadFail": "Kunde inte läsa filen.",
    "set.recoveryFound": "Vi hittade data från förra gången som inte kunde läsas in.",
    "set.recoveryDownload": "Ladda ner den",
    "set.recoveryDismiss": "Avfärda",
    "save.failedBanner": "Kunde inte spara — webbläsarens lagring kan vara full.",
    "save.emergencyExport": "Ladda ner en säkerhetskopia nu",
    "boot.failedTitle": "StudyBuddy kunde inte starta",
    "boot.failedBody": "Något gick fel när dina sparade data skulle läsas in. Dina data finns förmodligen kvar på den här enheten.",
    "boot.reload": "Försök ladda om",
    "boot.downloadData": "Ladda ner dina sparade data",
    "set.roadmap": "Kommande",
    "set.roadVoice": "Röstchatt — prata igenom uppgifter högt",
    "set.roadAccounts": "Konton & synk — använd StudyBuddy på alla enheter",
    "set.roadTeacher": "Förälder-/lärarvy — dela ut uppgifter och följ framsteg",
    "set.roadShare": "Dela set med en kompis",

    /* ---- errors ---- */
    "err.network": "Nätverksfel — kolla din uppkoppling.",
    "err.badKey": "API-nyckeln godtogs inte. Kontrollera den i Inställningar.",
    "err.serverNoKey": "Handledarservern har ingen Claude-nyckel konfigurerad. Kontakta den som driver instansen.",
    "err.rateLimited": "API:et begränsade anropen — vänta en stund och försök igen.",
    "err.api": "API-fel {status}",
    "err.apiDetail": "API-fel {status}: {detail}",
    "err.tutorUnavailable": "Handledaren är otillgänglig (API {status}).",
    "err.pdfNoLib": "PDF-läsaren kunde inte laddas. Ladda om sidan och försök igen.",
    "err.pdfNoText": "Hittade ingen markerbar text i den PDF:en. Om det är en inskanning, ladda upp den som foto i stället.",
    "err.imageType": "Använd en PNG-, JPG-, WEBP- eller GIF-bild.",
    "err.imageSize": "Bilden är över 5 MB — testa ett mindre foto.",
    "err.readFile": "Kunde inte läsa filen.",
    "err.zipNoLib": "ZIP-läsaren kunde inte laddas. Ladda om sidan och försök igen.",
    "err.zipNoPdf": "Hittade ingen PDF i zip-filen.",
    "err.zipNoText": "Kunde inte läsa text ur PDF-filerna i zip-filen (kan vara skannade sidor).",

    "common.parent": "Förälder / lärare",

    "sync.conflict": "Synkade från en annan enhet — vissa lokala ändringar här ersattes.",

    "set.serverTitle": "Handledarserver",
    "set.serverBody": "Frågegenerering och live-handledning körs på en liten backend som håller Claude-nyckeln — inget att ställa in här. Utan den nåbar körs StudyBuddy i demoläge på exempelinnehållet.",
    "set.serverDown": "Inte nåbar — kör i demoläge",
    "set.serverNoKey": "Ansluten, men ingen Claude-nyckel konfigurerad — kör i demoläge",
    "set.serverLive": "Ansluten — live-läge är på",
    "set.dataBodySynced": "Allt (uppgifter, försök, framsteg) ligger i den här webbläsaren och synkas till ditt konto.",
    "set.acctTitle": "Konto",
    "set.acctSignedIn": "Inloggad som {email}. Ditt bibliotek synkas till det här kontot.",
    "set.acctSignedOut": "Inte inloggad — StudyBuddy fungerar helt lokalt. Logga in för att synka ditt bibliotek mellan enheter.",
    "set.acctSignIn": "Logga in / skapa konto",
    "set.acctSignOut": "Logga ut",
    "set.acctSignedOutToast": "Utloggad — lokalt läge",
    "set.acctParentLink": "Förälder-/lärarkoppling",
    "set.acctNoServer": "Handledarservern är inte nåbar, så inloggning fungerar inte just nu.",

    "session.nationalMixEmpty": "Inga importerade set för det här ämnet ännu.",
    "session.nationalMixTitle": "Blandat — {subject}",
    "session.nationalMixFallback": "Nationellt prov",
    "session.badgeNationalMix": "Nationellt prov",

    "create.optNational": "Nationellt prov",
    "create.optNationalSub": "Öva inför nationella prov",
    "create.pdfOrZipFile": "PDF- eller ZIP-fil",
    "create.zipExtracted": "Extraherade text från {n} av {total} PDF-filer i ”{name}”{audio}.",
    "create.zipSkippedAudio": " ({n} ljudfiler ignorerades)",
    "create.npLevel": "Nivå",
    "create.npLevelPlaceholder": "Välj nivå…",
    "create.npSubject": "Ämne",
    "create.npSubjectPlaceholder": "Välj ämne…",
    "create.npPasteText": "Klistra in text",
    "create.npPastePlaceholder": "Klistra in ett utdrag ur provet här (valfritt om du laddar upp filen nedan)…",
    "create.npInfoExternal": "Öppnar en universitetssida med gamla prov — hämta det du vill öva på (PDF, ZIP eller vad de erbjuder), ladda sedan upp eller klistra in det här.",
    "create.npInfoLimited": "Riktiga gamla prov i det här ämnet innehåller upphovsrättsskyddade texter, så bara exempeluppgifter är fritt publicerade — länken visar dem. Fullständiga gamla prov måste begäras ut från Skolverket som en ”begäran om allmän handling”.",
    "create.npGetMaterial": "Hämta provmaterial ↗",
    "create.npBadgeExample": "Exempel",
    "create.npBadgeExternal": "Extern sida",
    "create.npImportedOne": "{n} importerat set för det här ämnet:",
    "create.npImportedMany": "{n} importerade set för det här ämnet:",
    "create.npMixLabel": "Blanda alla år — antal frågor:",
    "create.npMixStart": "Starta blandning",
    "create.subjectLocked": "Låst till nationellt prov-ämne",
    "create.preferFlashcards": "Föredra flashcards",

    "login.title": "Konto",
    "login.intro": "Logga in för att synka ditt bibliotek och dina framsteg mellan enheter. Helt valfritt — StudyBuddy fungerar lokalt om du hoppar över det.",
    "login.email": "E-post",
    "login.password": "Lösenord",
    "login.passwordHint": "Minst 8 tecken",
    "login.signIn": "Logga in",
    "login.createAccount": "Skapa konto",
    "login.needAccount": "Behöver du ett konto? Skapa ett",
    "login.haveAccount": "Har du redan ett konto? Logga in",
    "login.signedInToast": "Inloggad — synkning är på",
    "login.createdToast": "Konto skapat — synkning är på",
    "login.serverDown": "Backend-servern är inte nåbar just nu — inloggning fungerar inte förrän den är det.",
    "login.somethingWrong": "Något gick fel.",
    "login.back": "Tillbaka till inställningar",

    "parent.title": "Förälder / lärare",
    "parent.signInPrompt": "Logga in för att koppla konton, dela ut uppgifter och se framsteg.",
    "parent.backToMenu": "Tillbaka till menyn",
    "parent.back": "Tillbaka",
    "parent.inviteHeading": "Bjud in en förälder",
    "parent.inviteIntro": "Skapa en kod och dela den med en förälder eller lärare så att de kan koppla till ditt konto.",
    "parent.inviteGenerate": "Skapa inbjudningskod",
    "parent.inviteShare": "Dela den här koden — den går ut om 30 minuter och fungerar en gång.",
    "parent.studentsHeading": "Elever du är kopplad till",
    "parent.studentsNone": "Inga ännu — lös in en elevs inbjudningskod nedan.",
    "parent.haveCode": "Har du en elevs inbjudningskod?",
    "parent.link": "Koppla",
    "parent.linkedToStudent": "Kopplad till {email}",
    "parent.assignSet": "Dela ut ett set",
    "parent.assign": "Dela ut",
    "parent.noOwnSets": "Du har inga egna set att dela ut ännu — skapa ett från menyn först.",
    "parent.assigned": "Delade ut ”{title}” till {email}",
    "parent.unlink": "Koppla bort",
    "parent.unlinkConfirm": "Koppla bort {email}?",
    "parent.parentsHeading": "Föräldrar / lärare kopplade till dig",
    "parent.parentsNone": "Ingen ännu. Skapa en kod ovan och dela den med en förälder eller lärare.",
    "parent.assignedToYouHeading": "Utdelat till dig",
    "parent.assignedLoadFail": "Kunde inte ladda utdelade set.",
    "parent.assignedNone": "Inget som väntar just nu.",
    "parent.addToLibrary": "Lägg till i mitt bibliotek",
    "parent.addedToLibrary": "La till ”{title}” i ditt bibliotek",
    "parent.fromWho": "från {email}",
    "parent.studentProgressTitle": "Elevens framsteg",
    "parent.notAvailable": "Inte tillgängligt",
    "parent.noDataTitle": "Ingen data ännu",
    "parent.noDataBody": "Den här eleven har inte synkat något ännu.",
    "parent.studyStreak": "Pluggsvit",
    "parent.streakDays": "{n} dagar",
    "parent.streakDay": "{n} dag",
    "parent.daysSessions": "{days} dag(ar) pluggade · {sessions} pass avklarade",
    "parent.masteryHeading": "Färdighet per ämne",
    "parent.noMastery": "Ingen färdighetsdata ännu.",
    "parent.dueHeading": "Att repetera",
    "parent.dueCount": "{n} fråga/frågor att repetera.",
    "parent.dueNone": "Inget att repetera just nu.",

    "common.undo": "Ångra",

    "cal.prevMonth": "Föregående månad",
    "cal.nextMonth": "Nästa månad",
    "cal.prevWeek": "Föregående vecka",
    "cal.nextWeek": "Nästa vecka",
    "datepick.tomorrow": "Imorgon",
    "datepick.in3days": "Om 3 dagar",
    "datepick.nextMon": "Nästa måndag",
    "datepick.in1week": "Om 1 vecka",
    "datepick.in2weeks": "Om 2 veckor",

    "menu.goalToday": "{done} / {goal} idag",
    "menu.goalDone": "Dagsmålet klart",
    "menu.goalSub": "Frågor besvarade idag",

    "prog.heatmapTitle": "Pluggdagar",
    "prog.heatmapSub": "De senaste 12 veckorna — ifyllda rutor är dagar du pluggade.",

    "set.dailyGoal": "Dagsmål (frågor)",
    "set.dailyGoalNote": "Ringen på startsidan och Framsteg fylls när du svarar på frågor varje dag. Sätt till 0 för att dölja den.",
    "set.dailyGoalUpdated": "Dagsmål uppdaterat",

    "common.view": "Visa",

    "streak.freezeHelp": "Streak-frysningar — var och en täcker en missad dag. Du får en för varje 7-dagarssvit, upp till två.",
    "streak.freezeNext": "nästa frysning om {n} dagar",
    "streak.freezeUsedToast": "Streak-frysning använd — din {n}-dagarssvit är räddad",
    "streak.frozenDay": "streak-frysning använd",
    "streak.atRisk": "Plugga idag för att behålla din {n}-dagarssvit — en frysning finns redo om du missar.",
    "streak.atRiskShort": "Svit i fara — plugga idag",

    "prog.achievements": "Utmärkelser",
    "prog.achProgress": "{have} / {need}",
    "prog.personalBest": "personbästa: {n} dagar",

    "ach.multiToast": "{n} utmärkelser upplåsta!",
    "ach.streak3.title": "På gång",
    "ach.streak3.desc": "En 3-dagarssvit.",
    "ach.streak7.title": "En vecka stark",
    "ach.streak7.desc": "En 7-dagarssvit.",
    "ach.streak30.title": "En månad av driv",
    "ach.streak30.desc": "En 30-dagarssvit.",
    "ach.streak100.title": "Ostoppbar",
    "ach.streak100.desc": "En 100-dagarssvit.",

    "set.saved": "Sparat",

    "q.confPrompt": "Hur säker var du?",
    "q.conf_guessed": "Gissade",
    "q.conf_unsure": "Osäker",
    "q.conf_knew": "Kunde det",
    "q.workedNailed": "Helt rätt",
    "q.workedRoughly": "Ungefär rätt",
    "q.workedMissed": "Missade",
    "q.blankAria": "Lucka {n}",
    "q.clozeMissed": "Inte riktigt. Ordet/orden som saknades:",
    "q.tutorClozeWrong": "Jag fyllde i luckorna men är inte säker på att de stämmer.",
    "q.mathKeypad": "Infoga en matematisk symbol",

    "session.testBannerHints": "Provläge: ett försök per fråga. Du kan fråga handledaren upp till {n} gånger.",
    "session.adaptiveEase": "Vi tar det lite lugnare — handledaren är här, och de närmaste frågorna spelar på dina styrkor.",
    "session.adaptiveCruise": "Det här går som en dans för dig.",
    "session.adaptiveFinishNow": "Avsluta nu",

    "tutor.hintsLeft": "{n} tips kvar i provet",
    "tutor.hintsGone": "Inga tips kvar i provet",

    "results.hintsUsedOne": "{n} tips använt",
    "results.hintsUsedMany": "{n} tips använda",

    "set.studying": "Studier",
    "set.testHints": "Tips under prov",
    "set.testHints0": "Inga — handledare av",
    "set.testHints1": "1 tips",
    "set.testHints2": "2 tips",
    "set.testHints3": "3 tips",
    "set.testHintsNote": "Hur många gånger handledaren svarar under ett prov innan den låses. Inga tips gör provet till ett riktigt prov.",
    "set.adaptive": "Anpassad övning",
    "set.adaptiveOn": "På",
    "set.adaptiveOff": "Av",
    "set.adaptiveNote": "Ett övningspass anpassar sig efter hur det går — öppnar handledaren om du kämpar, eller erbjuder att avsluta tidigt om det flyter på.",

    "ed.kindCloze": "Fyll i luckan",
    "ed.clozeHint": "Skriv meningen och omge varje ord som saknas med dubbla klammerparenteser, t.ex. Frankrikes huvudstad är {{Paris}}. Skilj alternativ med lodstreck: {{Paris|paris}}.",
    "ed.clozeCount": "{n} lucka/luckor",

    "prog.achCount": "{have} av {need} upplåsta",

    "ach.q50.title": "Uppvärmd",
    "ach.q50.desc": "Besvarade 50 frågor.",
    "ach.q250.title": "Beläst",
    "ach.q250.desc": "Besvarade 250 frågor.",
    "ach.q1000.title": "Lärd",
    "ach.q1000.desc": "Besvarade 1 000 frågor.",
    "ach.subj80.title": "Stark i ämnet",
    "ach.subj80.desc": "Tog ett ämne till 80 % färdighet.",
    "ach.subj100.title": "Bemästrad",
    "ach.subj100.desc": "Tog ett ämne till 100 % färdighet.",
    "ach.all60.title": "Allsidig",
    "ach.all60.desc": "Alla ämnen du pluggat ligger på 60 %+.",
    "ach.goalweek.title": "In i vanan",
    "ach.goalweek.desc": "Nådde dagsmålet 7 dagar i rad.",
    "ach.subj3.title": "Vidgar vyerna",
    "ach.subj3.desc": "Pluggade 3 olika ämnen.",
    "ach.subj5.title": "Mångsysslare",
    "ach.subj5.desc": "Pluggade 5 olika ämnen.",
    "ach.firstreview.title": "Återvänder till det",
    "ach.firstreview.desc": "Klarade ett repetitionspass.",
    "ach.firstfreeze.title": "Räddad av skölden",
    "ach.firstfreeze.desc": "Använde en streak-frysning.",

    "session.pomoTitle": "Fokustimer",
    "session.pomoDone": "Dags för en paus — bra fokus.",

    "recap.title": "Förra veckan",
    "recap.daysOne": "{n} dag pluggad",
    "recap.daysMany": "{n} dagar pluggade",
    "recap.qOne": "{n} fråga",
    "recap.qMany": "{n} frågor",
    "recap.topicsOne": "{n} område förbättrat",
    "recap.topicsMany": "{n} områden förbättrade",
    "recap.strongest": "{subject} är ditt starkaste",

    "set.pomodoro": "Fokustimer",
    "set.pomodoroOff": "Av",
    "set.pomodoro25": "25 minuter",
    "set.pomodoro50": "50 minuter",
    "set.pomodoroNote": "Visar en nedräkning under ett pluggpass och plingar mjukt när tiden är ute.",

    "set.font": "Typsnitt",
    "set.fontSystem": "Standard",
    "set.fontHyperlegible": "Hyperlegible",
    "set.textSize": "Textstorlek",
    "set.textSizeS": "Liten",
    "set.textSizeM": "Mellan",
    "set.textSizeL": "Stor",

    "ed.dragReorder": "Dra för att ändra ordning",
    "ed.moveUp": "Flytta fråga {n} uppåt",
    "ed.moveDown": "Flytta fråga {n} nedåt",

    "menu.itemPrint": "Skriv ut arbetsblad",

    "print.action": "Skriv ut / spara PDF",
    "print.name": "Namn",
    "print.date": "Datum",
    "print.answerKey": "Facit",

    "gallery.title": "Exempelset",
    "gallery.intro": "Färdiga set att prova innan du bygger egna. Lägger du till ett hamnar det i biblioteket som vilket set som helst.",
    "gallery.add": "Lägg till i biblioteket",
    "gallery.inLibrary": "Finns i biblioteket",
    "gallery.added": "La till ”{title}”",
    "gallery.questions": "{n} frågor",

    "onb.s1title": "Plugga på ditt eget material",
    "onb.s1body": "Klistra in anteckningar, ladda upp en PDF eller ett foto, eller skriv bara ett ämne — StudyBuddy gör om det till frågor.",
    "onb.s2title": "En handledare som frågar, inte säger",
    "onb.s2body": "Jobba dig igenom frågorna en i taget. Fastnar du? Handledaren ger tips, aldrig svaret — förrän du verkligen försökt.",
    "onb.s3title": "Repetition får det att fastna",
    "onb.s3body": "Frågor du hade fel på kommer tillbaka enligt ett schema. Din streak och dina framsteg håller koll på allt.",
    "onb.next": "Nästa",
    "onb.browse": "Bläddra bland exempelset",
    "onb.makeFirst": "Skapa mitt första set",

    "cmd.placeholder": "Hoppa till ett set eller en åtgärd…",
    "cmd.openSet": "Öppna set",
    "cmd.action": "Åtgärd",
    "cmd.review": "Repetera idag",
    "cmd.weak": "Öva svaga punkter",
    "cmd.new": "Nytt set",
    "cmd.gallery": "Exempelset",
    "cmd.progress": "Framsteg",
    "cmd.settings": "Inställningar",
    "cmd.lang": "Byt till {lang}",
    "cmd.theme": "Växla mörkt läge",

    "create.optImport": "Importera kort",
    "create.optImportSub": "Quizlet / Anki / CSV-export",
    "create.takePhoto": "Ta ett foto",
    "create.choosePhoto": "Välj en fil",
    "create.importPlaceholder": "term<tabb>definition, en per rad — eller klistra in en Quizlet-export här",
    "create.importHint": "Klistra in exporterade kort eller ladda upp en .csv. Term och definition kan delas med tabb, kommatecken eller \" - \".",
    "create.importPaste": "Klistra in kort",
    "create.importFile": "Eller ladda upp en fil",
    "create.importFound": "Hittade {n} kort",
    "create.importNone": "Kunde inte hitta några term-/definitionspar.",
    "create.importBuild": "Skapa setet",

    "create.optBlank": "Bygg själv",
    "create.optBlankSub": "Ett tomt set att fylla i — ingen AI",
    "create.blankHint": "Ger dig några redigerbara frågor av varje typ att börja med. Bra för att testa appen.",
    "create.blankBuild": "Skapa tomt set",
    "create.blankTitle": "Namnlöst set",
    "create.blankQ": "Exempelfråga {n} — redigera mig",
    "create.blankCloze": "Exempel {n}: Frankrikes huvudstad är {{Paris}}",
    "create.subjectPlaceholder": "Nytt ämne, eller välj ett nedan",
    "create.subjectExisting": "Befintliga ämnen",

    "create.needKeyShort": "Lägg till en Claude-nyckel i Inställningar för att använda detta",
    "create.splitFound": "Ser ut som {n} avsnitt här.",
    "create.splitEach": "Skapa ett set för varje ({n})",
    "create.splitTitle": "Skapar dina set",
    "create.splitSub": "Ett set per avsnitt — det tar en liten stund var.",
    "create.splitDone": "Skapade {n} set",

    "tutor.voiceStart": "Prata med handledaren",
    "tutor.voiceStop": "Sluta lyssna",
    "tutor.voiceListening": "Lyssnar…",
    "tutor.voiceListenUnsupported": "Den här webbläsaren stödjer inte röstinmatning",
    "tutor.explainWhyLabel": "Förklara varför mitt svar var fel",
    "tutor.explainWhyPrompt": "Jag svarade {answer} och det var fel. Förklara varför, och vad som är rätt tanke — upprepa inte bara svaret.",
    "tutor.explainWhyBlank": "ingenting",
    "tutor.explainWhyScripted": "Nu tittar vi på var det gick snett. Jämför ditt svar med facit ovan — vilken del stämmer inte, och varför?",

    "q.explainWhy": "Förklara varför",

    "set.voice": "Handledarens röst",
    "set.voiceOn": "Läs upp svaren",
    "set.voiceOff": "Av",
    "set.voiceNote": "När det är på läser handledaren upp sina svar. Mikrofonknappen låter dig svara högt.",
    "set.voiceUnsupported": "Den här webbläsaren stödjer inte tal, så röst är inte tillgängligt.",

    "edit.moreLike": "Lägg till fler som dessa",
    "edit.moreWorking": "Skriver fler frågor…",
    "edit.moreAdded": "La till {n} nya frågor — granska dem nedan.",
    "edit.moreFailed": "Kunde inte lägga till fler just nu. Försök igen om en stund.",

    "menu.itemMore": "Lägg till fler frågor",

    "teach.title": "Förklara det",
    "teach.intro": "Förklara {subject} med egna ord. Bästa sättet att veta att du verkligen kan det.",
    "teach.tile": "Förklara det",
    "teach.round": "Omgång {n} av {total}",
    "teach.ask": "Förklara ”{topic}” med egna ord.",
    "teach.placeholder": "Förklara det som för en klasskompis…",
    "teach.answerAria": "Din förklaring",
    "teach.submit": "Kolla min förklaring",
    "teach.checking": "Läser…",
    "teach.next": "Nästa ämne",
    "teach.finish": "Se hur det gick",
    "teach.gradePrompt": "Eleven ombads förklara ”{topic}” med egna ord.",
    "teach.rubric": "Full poäng för en tydlig, korrekt förklaring som visar verklig förståelse — formuleringen spelar ingen roll.",
    "teach.demoOk": "Det är en gedigen förklaring — du har helt klart greppet.",
    "teach.demoThin": "Bra början, men utveckla mer — berätta mer om hur och varför det fungerar.",
    "teach.doneTitle": "Snyggt jobbat",
    "teach.doneBody": "Du förklarade {correct} av {total} tydligt. Det är det som fastnar.",
    "teach.toProgress": "Tillbaka till framsteg",
    "teach.attemptTitle": "Förklarat: {subject}",
    "teach.goneTitle": "Inget att förklara än",
    "teach.goneBody": "Plugga ett ämne till 80 % behärskning så dyker det upp här.",

    "nav.home": "Hem",
    "nav.study": "Studera",
    "nav.calendar": "Kalender",
    "nav.library": "Bibliotek",
    "nav.create": "Skapa",
    "nav.leaveConfirm": "Lämna passet?\n\nDina framsteg sparas — du kommer tillbaka exakt där du slutade.",
    "nav.leave": "Lämna",
    "nav.stay": "Stanna kvar",
    "common.confirm": "Bekräfta",
    "common.menu": "Meny",

    "session.testOff": "Stäng av provläge",
    "session.testOn": "Sätt på provläge igen",
    "session.testOffConfirm": "Stänga av provläge?\n\nDu får tillgång till handledaren och ett andra försök på varje fråga, och detta sparas inte som ett provresultat.",
    "session.testOffToast": "Provläge av — handledaren finns här för att hjälpa.",
    "session.testOnToast": "Provläge på igen.",
    "session.testModeOff": "Provläge är avstängt för den här omgången.",

    "session.examBanner": "Provläge — nedräkning, ett försök per fråga och inga tips. Handledaren går igenom allt med dig efteråt.",
    "session.examBadge": "Provläge",
    "session.examTimeUp": "Tiden är ute — dina svar skickades in automatiskt.",

    "common.library": "Övningsbibliotek",
    "lib.title": "Övningsbibliotek",
    "lib.loadFail": "Kunde inte ladda biblioteket",
    "lib.loadFailBody": "Försök igen om en stund.",
    "lib.search": "Sök i biblioteket — ämne, kurs eller set…",
    "lib.searchAria": "Sök i övningsbiblioteket",
    "lib.intro": "Färdiga övningar du kan börja plugga på direkt — ingen egen uppladdning behövs. Välj nivå för att se ämnen.",
    "lib.pickSubject": "{level} — vilket ämne vill du plugga?",
    "lib.noHits": "Inga träffar för ”{q}”. Prova ett ämne, en kurs eller en årskurs.",
    "lib.hitsOne": "{n} träff",
    "lib.hitsMany": "{n} träffar",
    "lib.add": "Lägg till",
    "lib.study": "Plugga",
    "lib.exam": "Provläge",
    "lib.examTip": "Provläge: nedräkning, inga ledtrådar och facit visas först när du är klar.",
    "lib.added": "”{title}” tillagt",
    "lib.addFail": "Kunde inte lägga till setet",
    "lib.addAll": "Lägg till alla ({n})",
    "lib.addedN": "La till {n} set",
    "lib.allThere": "Allt fanns redan i ditt bibliotek",
    "lib.allAdded": "Alla set tillagda ✓",
    "lib.examLenLabel": "Tidsgräns",
    "lib.examLenNone": "Ingen gräns (räknar upp)",
    "lib.examStart": "Starta provet",

    "menu.libraryCta": "Öppna övningsbiblioteket",
    "menu.libraryLink": "Övningsbibliotek",

    "results.examSuffix": " · provläge",
    "results.examLimit": " (gräns {n} min)",
    "results.timedOut": "Tiden tog slut — detta skickades in automatiskt.",
  },
};
